In [3]:
import pdfplumber

def group_words_into_lines(words, y_tolerance=2.0):
    """
    Group words into lines by their top position, within a y_tolerance.
    """
    lines = []
    
    # Sort words top to bottom, then left to right
    words_sorted = sorted(words, key=lambda w: (w['top'], w['x0']))

    current_line = []
    current_top = None

    for word in words_sorted:
        word_top = word['top']
        
        if current_line == []:
            # Start a new line
            current_line = [word]
            current_top = word_top
        else:
            if abs(word_top - current_top) <= y_tolerance:
                current_line.append(word)
            else:
                # Finish the current line
                lines.append(current_line)
                # Start a new line
                current_line = [word]
                current_top = word_top
    
    # Add last line
    if current_line:
        lines.append(current_line)

    return lines

# Open the PDF
with pdfplumber.open(r"C:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\Fashionova\B158_91060_20230815_V1916.pdf") as pdf:
    page = pdf.pages[0]
    words = page.extract_words()

    # Group words into lines
    lines = group_words_into_lines(words)

    # Output line info
    for line_words in lines:
        x0 = min(w['x0'] for w in line_words)
        x1 = max(w['x1'] for w in line_words)
        top = min(w['top'] for w in line_words)
        bottom = max(w['bottom'] for w in line_words)
        text = " ".join(w['text'] for w in line_words)
        print(f"Line: '{text}' | x0: {x0:.2f} | top: {top:.2f} | x1: {x1:.2f} | bottom: {bottom:.2f}")

Line: 'Bill To : CW Management Pty Ltd B655' | x0: 27.84 | top: 114.57 | x1: 235.61 | bottom: 125.10
Line: 'Customer No. : PH1871' | x0: 370.79 | top: 117.45 | x1: 508.61 | bottom: 127.98
Line: 'Invoice No. : 91060' | x0: 370.79 | top: 133.65 | x1: 499.76 | bottom: 144.18
Line: 'Ship To : Chemist Warehouse Townsville B158' | x0: 27.84 | top: 137.49 | x1: 271.91 | bottom: 148.02
Line: 'Invoice Date : 15.08.23' | x0: 370.79 | top: 149.97 | x1: 511.45 | bottom: 160.50
Line: '126-128 Sturt St Address :' | x0: 28.80 | top: 157.65 | x1: 165.02 | bottom: 169.15
Line: 'Due Date : 30.09.23' | x0: 370.79 | top: 166.29 | x1: 511.45 | bottom: 176.82
Line: 'TOWNSVILLE QLD 4810' | x0: 85.32 | top: 171.09 | x1: 206.26 | bottom: 181.63
Line: 'Invoice Amount : $ 187.25 AUD AUSTRALIA' | x0: 85.32 | top: 182.49 | x1: 558.13 | bottom: 194.94
Line: 'TTAAXX IINNVVOOIICCEE' | x0: 265.92 | top: 230.83 | x1: 341.31 | bottom: 245.19
Line: 'PPaaggee 11 ooff 11' | x0: 494.16 | top: 237.61 | x1: 566.24 | bottom: 247.18
Line: 'UUnniitt TToottaall TToottaall' | x0: 442.19 | top: 253.99 | x1: 562.13 | bottom: 261.65
Line: 'NNoo.. PPeeggNNoo.. TTyyppee NNoo.. SSiizzee CCoolloouurr DDeessccrriippttiioonn QQ''ttyy UUnniitt GGSSTT' | x0: 21.12 | top: 261.11 | x1: 528.23 | bottom: 270.69
Line: 'PPrriiccee eexxccll..GGSSTT IInnccll..GGSSTT' | x0: 440.63 | top: 266.47 | x1: 567.59 | bottom: 274.13
Line: 'DD0088 33--99 NN..PPKK//OORR//YYLLLLaaddiieess'' CCaassuuaall LLooww ccuutt 11 DDzz $$4422..7788 $$4422..7788 $$44..2288 $$4477..0066 11 TTNN11--001122LL--CC11' | x0: 21.12 | top: 281.27 | x1: 569.10 | bottom: 290.85
Line: 'DD1122 77--1111 MMeenn''ss CCaassuuaall AAnnkklleett 11 DDzz $$4422..7788 $$4422..7788 $$44..2288 $$4477..0066 22 TTNN22--000022MM--BB11 WWHH' | x0: 21.12 | top: 292.68 | x1: 569.10 | bottom: 302.25
Line: 'PPDD0033 1111--1144 MMeenn''ss BBuussiinneessss DDiiaabbeettiicc FFrriieennddllyy EExxttrraa LLaarrggee 11 DDzz $$6644..1177 $$6644..1177 $$66..4422 $$7700..5599 33 BBUU44--000022KK--CC22 BBKK' | x0: 21.12 | top: 304.19 | x1: 569.10 | bottom: 313.77
Line: 'CCOOUU CCoouurriieerr FFeeee 11 BBooxx $$2200..5500 $$2200..5500 $$22..0055 $$2222..5555 44 CCOOUU' | x0: 21.12 | top: 315.72 | x1: 569.10 | bottom: 325.29
Line: 'Dz $170.23 $17.02 $187.25 Total Q'ty 3 SATCHEL*1' | x0: 24.00 | top: 330.12 | x1: 569.81 | bottom: 341.62
Line: 'Total (GST Incl.) $187.25 RE-ORDERS & GENERAL ENQUIRIES' | x0: 25.92 | top: 413.37 | x1: 570.90 | bottom: 424.78
Line: 'o RE-ORDERS 30.09.23 Due Date - Please fax through Re-Order Form to 02 9748 6211' | x0: 25.92 | top: 430.16 | x1: 570.97 | bottom: 442.15
Line: '$0.00 Last Balance' | x0: 390.84 | top: 445.88 | x1: 570.96 | bottom: 457.38
Line: 'for your next order. New Re-Order Forms are supplied with this delivery.' | x0: 36.36 | top: 448.28 | x1: 343.91 | bottom: 457.85
Line: 'Current Payment $0.00 o ENQUIRIES' | x0: 25.92 | top: 464.13 | x1: 570.98 | bottom: 475.71
Line: '- Please contact FASHIONOVA at 029748 6222' | x0: 105.36 | top: 467.48 | x1: 303.53 | bottom: 477.05
Line: 'Leave your general enquiry on www.soxnlox.com $187.25' | x0: 37.32 | top: 480.92 | x1: 571.02 | bottom: 493.95
Line: 'Total Balance' | x0: 390.84 | top: 483.41 | x1: 465.52 | bottom: 494.91
Line: 'or e-mail to info@fashionova.com.au' | x0: 37.32 | top: 492.32 | x1: 196.04 | bottom: 501.89
Line: 'o All display stands will remain the property of Fashionova Pty Ltd.' | x0: 25.92 | top: 512.48 | x1: 308.18 | bottom: 522.05
Line: 'How to pay this invoice Fashionova Pty Ltd ABN : 96 125 037 434' | x0: 25.92 | top: 591.82 | x1: 537.37 | bottom: 603.31
Line: 'Electronic Funds Transfer Cheque in the Mail' | x0: 25.92 | top: 618.25 | x1: 255.09 | bottom: 628.78
Line: 'Credit Card Payment' | x0: 329.52 | top: 621.13 | x1: 423.92 | bottom: 630.70
Line: 'For Visa & Mastercard payments, please complete the Preferred Method of Payment' | x0: 25.92 | top: 634.04 | x1: 515.73 | bottom: 642.74
Line: 'Please make your cheque payable' | x0: 170.52 | top: 638.93 | x1: 302.67 | bottom: 647.55
Line: 'following and mail or fax back to 02 9748 6211:' | x0: 329.52 | top: 643.52 | x1: 491.59 | bottom: 651.18
Line: 'to Fashionova Pty Ltd Account ......: Fashionova Pty Ltd' | x0: 25.92 | top: 648.85 | x1: 289.36 | bottom: 658.94
Line: 'Visa ____ Mastercard ____ Expiry:_______/_______' | x0: 332.40 | top: 658.00 | x1: 540.86 | bottom: 666.62
Line: 'Bank ...........: CBA' | x0: 25.92 | top: 661.84 | x1: 96.94 | bottom: 670.46
Line: '(T/A SOX & LOX)' | x0: 199.32 | top: 665.69 | x1: 266.86 | bottom: 674.31
Line: 'BSB/Acc No : 062 256/1042 5214' | x0: 25.92 | top: 673.36 | x1: 155.05 | bottom: 681.98
Line: 'Name on card: _______________________________' | x0: 332.40 | top: 681.04 | x1: 540.08 | bottom: 689.66
Line: 'Unit 3 / 10-11 Millennium * Please quote your' | x0: 25.92 | top: 685.12 | x1: 275.24 | bottom: 694.47
Line: 'Court Silverwater NSW 2128 Customer NO .:' | x0: 25.92 | top: 695.56 | x1: 290.30 | bottom: 705.86
Line: 'PH1871' | x0: 93.84 | top: 700.36 | x1: 125.02 | bottom: 708.98
Line: 'Card#: ______________________________________' | x0: 332.40 | top: 703.97 | x1: 543.10 | bottom: 712.59
Line: 'Or Invoice NO :' | x0: 25.92 | top: 708.76 | x1: 85.56 | bottom: 717.38
Line: '91060' | x0: 93.84 | top: 710.92 | x1: 117.86 | bottom: 719.54
Line: 'for the payment.' | x0: 25.92 | top: 720.28 | x1: 88.15 | bottom: 728.90
Line: 'Please note: 1.88% credit card surcharge applies.' | x0: 354.48 | top: 724.04 | x1: 525.06 | bottom: 731.71
Line: 'Page 1 of 1' | x0: 38.16 | top: 828.61 | x1: 104.42 | bottom: 838.18

In [4]:
import pdfplumber
from difflib import SequenceMatcher

# Keywords
HEADER_KEYWORDS = ["description", "desc", "qty", "quantity", "item no", "code", "product", "uom", "unit"]
FOOTER_KEYWORDS = ["subtotal", "total", "grand total", "gst", "tax"]

def fuzzy_match(needle, haystack, threshold=0.7):
    """Fuzzy match a keyword against a line, return True if close enough."""
    return SequenceMatcher(None, needle, haystack).ratio() >= threshold

def group_words_to_lines(words, y_tolerance=3):
    """Group words into lines by Y position (with tolerance for slight variation)."""
    lines = {}
    for w in words:
        y_key = round(w["top"] / y_tolerance) * y_tolerance
        if y_key not in lines:
            lines[y_key] = []
        lines[y_key].append(w)
    return lines

# Open PDF
with pdfplumber.open(r"C:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\Fashionova\B158_91060_20230815_V1916.pdf") as pdf:
    page = pdf.pages[0]
    words = page.extract_words()

    # Group words into lines
    grouped_lines = group_words_to_lines(words)

    header_y = None
    footer_y = None

    # Detect header/footer lines
    for y, line_words in sorted(grouped_lines.items()):
        # Rebuild line text
        line_text = " ".join(w["text"] for w in sorted(line_words, key=lambda w: w["x0"]))
        line_text_lower = line_text.lower()
        print(f"[Y={y}] {line_text}")  # Debug: print every reconstructed line

        # Header detection with fuzzy match
        if header_y is None:
            for kw in HEADER_KEYWORDS:
                if fuzzy_match(kw, line_text_lower):
                    header_y = min(w["top"] for w in line_words)
                    print(f"✅ Fuzzy matched table header at Y: {header_y} | Line: {line_text}")
                    break

        # Footer detection (exact match for totals)
        if footer_y is None:
            if any(kw in line_text_lower for kw in FOOTER_KEYWORDS):
                footer_y = min(w["top"] for w in line_words)
                print(f"✅ Found table footer at Y: {footer_y} | Line: {line_text}")

    # Heuristic fallback if header not found
    if header_y is None and footer_y is not None:
        header_y = footer_y - 100
        print(f"⚠️ Header not found. Assuming header Y at {header_y} based on footer.")

    # Segment areas
    top_area = [w for w in words if header_y is not None and w["top"] < header_y]
    line_items_area = [w for w in words if header_y is not None and footer_y is not None and header_y <= w["top"] <= footer_y]
    bottom_area = [w for w in words if footer_y is not None and w["top"] > footer_y]

    # Print segmented areas
    print("\n=== TOP AREA ===")
    for w in top_area:
        print(f"{w['text']} at Y: {w['top']}")

    print("\n=== LINE ITEMS AREA ===")
    for w in line_items_area:
        print(f"{w['text']} at Y: {w['top']}")

    print("\n=== BOTTOM AREA ===")
    for w in bottom_area:
        print(f"{w['text']} at Y: {w['top']}")

[Y=114] Bill To : CW Management Pty Ltd B655
[Y=117] Customer No. : PH1871
[Y=135] Invoice No. : 91060
[Y=138] Ship To : Chemist Warehouse Townsville B158
[Y=150] Invoice Date : 15.08.23
[Y=159] Address : 126-128 Sturt St
[Y=165] Due Date : 30.09.23
[Y=171] TOWNSVILLE QLD 4810
[Y=183] AUSTRALIA Invoice Amount : $ 187.25 AUD
[Y=231] TTAAXX IINNVVOOIICCEE
[Y=237] PPaaggee 11 ooff 11
[Y=255] UUnniitt TToottaall TToottaall
[Y=261] NNoo.. PPeeggNNoo.. TTyyppee NNoo.. SSiizzee CCoolloouurr DDeessccrriippttiioonn QQ''ttyy UUnniitt GGSSTT
[Y=267] PPrriiccee eexxccll..GGSSTT IInnccll..GGSSTT
[Y=282] 11 DD0088 TTNN11--001122LL--CC11 33--99 NN..PPKK//OORR//YYLLLLaaddiieess'' CCaassuuaall LLooww ccuutt 11 DDzz $$4422..7788 $$4422..7788 $$44..2288 $$4477..0066
[Y=294] 22 DD1122 TTNN22--000022MM--BB11 77--1111 WWHH MMeenn''ss CCaassuuaall AAnnkklleett 11 DDzz $$4422..7788 $$4422..7788 $$44..2288 $$4477..0066
[Y=303] PPDD0033 1111--1144 MMeenn''ss BBuussiinneessss DDiiaabbeettiicc FFrriieennddllyy EExxttrraa LLaarrggee 11 DDzz $$6644..1177 $$6644..1177 $$66..4422 $$7700..5599
[Y=306] 33 BBUU44--000022KK--CC22 BBKK
[Y=315] 44 CCOOUU CCOOUU CCoouurriieerr FFeeee 11 BBooxx $$2200..5500 $$2200..5500 $$22..0055 $$2222..5555
[Y=330] Total Q'ty 3 Dz $170.23 $17.02 $187.25
✅ Found table footer at Y: 330.11649594872347 | Line: Total Q'ty 3 Dz $170.23 $17.02 $187.25
[Y=333] SATCHEL*1
[Y=414] RE-ORDERS & GENERAL ENQUIRIES Total (GST Incl.) $187.25
[Y=429] o RE-ORDERS
[Y=432] - Please fax through Re-Order Form to 02 9748 6211 Due Date 30.09.23
[Y=447] for your next order. New Re-Order Forms are supplied with this delivery. Last Balance $0.00
[Y=465] o ENQUIRIES Current Payment $0.00
[Y=468] - Please contact FASHIONOVA at 029748 6222
[Y=480] Leave your general enquiry on www.soxnlox.com
[Y=483] Total Balance $187.25
[Y=492] or e-mail to info@fashionova.com.au
[Y=513] o All display stands will remain the property of Fashionova Pty Ltd.
[Y=591] How to pay this invoice Fashionova Pty Ltd ABN : 96 125 037 434
[Y=618] Electronic Funds Transfer Cheque in the Mail
[Y=621] Credit Card Payment
[Y=633] Preferred Method of Payment For Visa & Mastercard payments, please complete the
[Y=639] Please make your cheque payable
[Y=645] following and mail or fax back to 02 9748 6211:
[Y=648] to Fashionova Pty Ltd
[Y=651] Account ......: Fashionova Pty Ltd
[Y=657] Visa ____ Mastercard ____ Expiry:_______/_______
[Y=663] Bank ...........: CBA
[Y=666] (T/A SOX & LOX)
[Y=672] BSB/Acc No : 062 256/1042 5214
[Y=681] Name on card: _______________________________
[Y=684] Unit 3 / 10-11 Millennium
[Y=687] * Please quote your
[Y=696] Customer NO .: Court Silverwater NSW 2128
[Y=699] PH1871
[Y=705] Card#: ______________________________________
[Y=708] Or Invoice NO :
[Y=711] 91060
[Y=720] for the payment.
[Y=723] Please note: 1.88% credit card surcharge applies.
[Y=828] Page 1 of 1
⚠️ Header not found. Assuming header Y at 230.11649594872347 based on footer.

=== TOP AREA ===
Bill at Y: 114.56623948227195
To at Y: 114.56623948227195
: at Y: 114.56623948227195
CW at Y: 114.56623948227195
Management at Y: 114.56623948227195
Pty at Y: 114.56623948227195
Ltd at Y: 114.56623948227195
B655 at Y: 114.56623948227195
Customer at Y: 117.44697223306991
No. at Y: 117.44697223306991
: at Y: 117.44697223306991
PH1871 at Y: 117.44697223306991
Invoice at Y: 133.64592702536288
No. at Y: 133.64592702536288
: at Y: 133.64592702536288
91060 at Y: 133.64592702536288
Ship at Y: 137.48861518838294
To at Y: 137.48861518838294
: at Y: 137.48861518838294
Chemist at Y: 137.48861518838294
Warehouse at Y: 137.48861518838294
Townsville at Y: 137.48861518838294
B158 at Y: 137.48861518838294
Invoice at Y: 149.96835236393895
Date at Y: 149.96835236393895
: at Y: 149.96835236393895
15.08.23 at Y: 149.96835236393895
Address at Y: 158.61053489449387
: at Y: 158.61053489449387
126-128 at Y: 157.648579482272
Sturt at Y: 157.648579482272
St at Y: 157.648579482272
Due at Y: 166.28562852695893
Date at Y: 166.28562852695893
: at Y: 166.28562852695893
30.09.23 at Y: 166.28562852695893
TOWNSVILLE at Y: 171.09027207004988
QLD at Y: 171.09027207004988
4810 at Y: 171.09027207004988
AUSTRALIA at Y: 184.40850983338396
Invoice at Y: 182.48973252695896
Amount at Y: 182.48973252695896
: at Y: 182.48973252695896
$ at Y: 182.48973252695896
187.25 at Y: 182.48973252695896
AUD at Y: 182.48973252695896

=== LINE ITEMS AREA ===
TTAAXX at Y: 230.82727132313926
IINNVVOOIICCEE at Y: 230.82727132313926
PPaaggee at Y: 237.60521835638053
11 at Y: 237.60521835638053
ooff at Y: 237.60521835638053
11 at Y: 237.60521835638053
UUnniitt at Y: 253.98886099085144
TToottaall at Y: 253.98886099085144
TToottaall at Y: 253.98886099085144
NNoo.. at Y: 261.1138781912815
PPeeggNNoo.. at Y: 261.1138781912815
TTyyppee at Y: 261.1138781912815
NNoo.. at Y: 261.1138781912815
SSiizzee at Y: 261.1138781912815
CCoolloouurr at Y: 261.1138781912815
DDeessccrriippttiioonn at Y: 261.1138781912815
QQ''ttyy at Y: 261.1138781912815
UUnniitt at Y: 261.1138781912815
GGSSTT at Y: 261.1138781912815
PPrriiccee at Y: 266.4705912261619
eexxccll..GGSSTT at Y: 266.4705912261619
IInnccll..GGSSTT at Y: 266.4705912261619
11 at Y: 281.6808708164748
DD0088 at Y: 281.2743490426428
TTNN11--001122LL--CC11 at Y: 281.911646495442
33--99 at Y: 281.2743490426428
NN..PPKK//OORR//YYLLLLaaddiieess'' at Y: 281.2743490426428
CCaassuuaall at Y: 281.2743490426428
LLooww at Y: 281.2743490426428
ccuutt at Y: 281.2743490426428
11 at Y: 281.2743490426428
DDzz at Y: 281.2743490426428
$$4422..7788 at Y: 281.2743490426428
$$4422..7788 at Y: 281.2743490426428
$$44..2288 at Y: 281.2743490426428
$$4477..0066 at Y: 281.2743490426428
22 at Y: 293.08168480192535
DD1122 at Y: 292.67510769872354
TTNN22--000022MM--BB11 at Y: 293.31243478041904
77--1111 at Y: 292.67510769872354
WWHH at Y: 293.31243478041904
MMeenn''ss at Y: 292.67510769872354
CCaassuuaall at Y: 292.67510769872354
AAnnkklleett at Y: 292.67510769872354
11 at Y: 292.67510769872354
DDzz at Y: 292.67510769872354
$$4422..7788 at Y: 292.67510769872354
$$4422..7788 at Y: 292.67510769872354
$$44..2288 at Y: 292.67510769872354
$$4477..0066 at Y: 292.67510769872354
33 at Y: 304.6008735373757
PPDD0033 at Y: 304.19397815147795
BBUU44--000022KK--CC22 at Y: 304.8316235158695
1111--1144 at Y: 304.19397815147795
BBKK at Y: 304.8316235158695
MMeenn''ss at Y: 304.19397815147795
BBuussiinneessss at Y: 304.19397815147795
DDiiaabbeettiicc at Y: 304.19397815147795
FFrriieennddllyy at Y: 304.19397815147795
EExxttrraa at Y: 304.19397815147795
LLaarrggee at Y: 304.19397815147795
11 at Y: 304.19397815147795
DDzz at Y: 304.19397815147795
$$6644..1177 at Y: 304.19397815147795
$$6644..1177 at Y: 304.19397815147795
$$66..4422 at Y: 304.19397815147795
$$7700..5599 at Y: 304.19397815147795
44 at Y: 316.1200365723528
CCOOUU at Y: 315.71573144498655
CCOOUU at Y: 316.3534325158695
CCoouurriieerr at Y: 315.71573144498655
FFeeee at Y: 315.71573144498655
11 at Y: 315.71573144498655
BBooxx at Y: 315.71573144498655
$$2200..5500 at Y: 315.71573144498655
$$2200..5500 at Y: 315.71573144498655
$$22..0055 at Y: 315.71573144498655
$$2222..5555 at Y: 315.71573144498655
Dz at Y: 330.11649594872347
$170.23 at Y: 330.11649594872347
$17.02 at Y: 330.11649594872347
$187.25 at Y: 330.11649594872347

=== BOTTOM AREA ===
SATCHEL*1 at Y: 332.04346378923333
Total at Y: 330.60833958647885
Q'ty at Y: 330.60833958647885
3 at Y: 330.60833958647885
RE-ORDERS at Y: 415.20659778549634
& at Y: 415.20659778549634
GENERAL at Y: 415.20659778549634
ENQUIRIES at Y: 415.20659778549634
Total at Y: 413.37056903949497
(GST at Y: 413.37056903949497
Incl.) at Y: 413.37056903949497
$187.25 at Y: 413.37056903949497
o at Y: 430.15571389770184
RE-ORDERS at Y: 430.15571389770184
- at Y: 432.0760156222106
Please at Y: 432.0760156222106
fax at Y: 432.0760156222106
through at Y: 432.0760156222106
Re-Order at Y: 432.0760156222106
Form at Y: 432.0760156222106
to at Y: 432.0760156222106
02 at Y: 432.0760156222106
9748 at Y: 432.0760156222106
6211 at Y: 432.0760156222106
Due at Y: 431.60982507004996
Date at Y: 431.60982507004996
30.09.23 at Y: 430.648497599009
for at Y: 448.27722889770183
your at Y: 448.27722889770183
next at Y: 448.27722889770183
order. at Y: 448.27722889770183
New at Y: 448.27722889770183
Re-Order at Y: 448.27722889770183
Forms at Y: 448.27722889770183
are at Y: 448.27722889770183
supplied at Y: 448.27722889770183
with at Y: 448.27722889770183
this at Y: 448.27722889770183
delivery. at Y: 448.27722889770183
Last at Y: 446.84939907004997
Balance at Y: 446.84939907004997
$0.00 at Y: 445.88486907005
o at Y: 465.5569759972106
ENQUIRIES at Y: 465.5569759972106
- at Y: 467.4772777217193
Please at Y: 467.4772777217193
contact at Y: 467.4772777217193
FASHIONOVA at Y: 467.4772777217193
at at Y: 467.4772777217193
029748 at Y: 467.4772777217193
6222 at Y: 467.4772777217193
Current at Y: 464.1273590410909
Payment at Y: 464.1273590410909
$0.00 at Y: 464.2137345429486
Leave at Y: 480.91933276896486
your at Y: 480.91933276896486
general at Y: 480.91933276896486
enquiry at Y: 480.91933276896486
on at Y: 480.91933276896486
www.soxnlox.com at Y: 480.91933276896486
Total at Y: 483.4130847397311
Balance at Y: 483.4130847397311
$187.25 at Y: 482.45208454294857
or at Y: 492.31543887221056
e-mail at Y: 492.31543887221056
to at Y: 492.31543887221056
info@fashionova.com.au at Y: 492.31543887221056
o at Y: 512.4771085494739
All at Y: 512.4771085494739
display at Y: 512.4771085494739
stands at Y: 512.4771085494739
will at Y: 512.4771085494739
remain at Y: 512.4771085494739
the at Y: 512.4771085494739
property at Y: 512.4771085494739
of at Y: 512.4771085494739
Fashionova at Y: 512.4771085494739
Pty at Y: 512.4771085494739
Ltd. at Y: 512.4771085494739
How at Y: 591.8194813872517
to at Y: 591.8194813872517
pay at Y: 591.8194813872517
this at Y: 591.8194813872517
invoice at Y: 591.8194813872517
Fashionova at Y: 592.4466772587243
Pty at Y: 592.4466772587243
Ltd at Y: 592.4466772587243
ABN at Y: 592.4466772587243
: at Y: 592.4466772587243
96 at Y: 592.4466772587243
125 at Y: 592.4466772587243
037 at Y: 592.4466772587243
434 at Y: 592.4466772587243
Electronic at Y: 618.2464877892332
Funds at Y: 618.2464877892332
Transfer at Y: 618.2464877892332
Cheque at Y: 619.2051401337242
in at Y: 619.2051401337242
the at Y: 619.2051401337242
Mail at Y: 619.2051401337242
Credit at Y: 621.1254704142334
Card at Y: 621.1254704142334
Payment at Y: 621.1254704142334
Preferred at Y: 634.1219598164748
Method at Y: 634.1219598164748
of at Y: 634.1219598164748
Payment at Y: 634.1219598164748
For at Y: 634.0433919105183
Visa at Y: 634.0433919105183
& at Y: 634.0433919105183
Mastercard at Y: 634.0433919105183
payments, at Y: 634.0433919105183
please at Y: 634.0433919105183
complete at Y: 634.0433919105183
the at Y: 634.0433919105183
Please at Y: 638.9253338573299
make at Y: 638.9253338573299
your at Y: 638.9253338573299
cheque at Y: 638.9253338573299
payable at Y: 638.9253338573299
following at Y: 643.5203930809353
and at Y: 643.5203930809353
mail at Y: 643.5203930809353
or at Y: 643.5203930809353
fax at Y: 643.5203930809353
back at Y: 643.5203930809353
to at Y: 643.5203930809353
02 at Y: 643.5203930809353
9748 at Y: 643.5203930809353
6211: at Y: 643.5203930809353
Account at Y: 650.3235275519253
......: at Y: 650.3235275519253
Fashionova at Y: 650.3235275519253
Pty at Y: 650.3235275519253
Ltd at Y: 650.3235275519253
to at Y: 648.845554113251
Fashionova at Y: 648.845554113251
Pty at Y: 648.845554113251
Ltd at Y: 648.845554113251
Visa at Y: 658.0047335519253
____ at Y: 658.0047335519253
Mastercard at Y: 658.0047335519253
____ at Y: 658.0047335519253
Expiry:_______/_______ at Y: 658.0047335519253
Bank at Y: 661.8427162873759
...........: at Y: 661.8427162873759
CBA at Y: 661.8427162873759
(T/A at Y: 665.6859395519255
SOX at Y: 665.6859395519255
& at Y: 665.6859395519255
LOX) at Y: 665.6859395519255
BSB/Acc at Y: 673.3619049965209
No at Y: 673.3619049965209
: at Y: 673.3619049965209
062 at Y: 673.3619049965209
256/1042 at Y: 673.3619049965209
5214 at Y: 673.3619049965209
Name at Y: 681.0431109965209
on at Y: 681.0431109965209
card: at Y: 681.0431109965209
_______________________________ at Y: 681.0431109965209
* at Y: 685.8464850373759
Please at Y: 685.8464850373759
quote at Y: 685.8464850373759
your at Y: 685.8464850373759
Unit at Y: 685.1230837873759
3 at Y: 685.1230837873759
/ at Y: 685.1230837873759
10-11 at Y: 685.1230837873759
Millennium at Y: 685.1230837873759
Customer at Y: 697.2446273573298
NO at Y: 697.2446273573298
.: at Y: 697.2446273573298
Court at Y: 695.5637469965209
Silverwater at Y: 695.5637469965209
NSW at Y: 695.5637469965209
2128 at Y: 695.5637469965209
PH1871 at Y: 700.3618291073299
Card#: at Y: 703.9656826073299
______________________________________ at Y: 703.9656826073299
Or at Y: 708.7638160664749
Invoice at Y: 708.7638160664749
NO at Y: 708.7638160664749
: at Y: 708.7638160664749
91060 at Y: 710.9234873573298
for at Y: 720.2830048019255
the at Y: 720.2830048019255
payment. at Y: 720.2830048019255
Please at Y: 724.0435966605182
note: at Y: 724.0435966605182
1.88% at Y: 724.0435966605182
credit at Y: 724.0435966605182
card at Y: 724.0435966605182
surcharge at Y: 724.0435966605182
applies. at Y: 724.0435966605182
Page at Y: 828.6051144359875
1 at Y: 828.6051144359875
of at Y: 828.6051144359875
1 at Y: 828.6051144359875

In [24]:
import fitz  # PyMuPDF

# Define your keywords
HEADER_KEYWORDS = ["description", "qty", "q'ty", "unit", "item", "no", "colour", "code", "total"]
FOOTER_KEYWORDS = ["total", "subtotal", "gst", "amount", "grand total"]

def print_blocks(title, blocks):
    print(f"\n=== {title.upper()} ===")
    for b in blocks:
        y = b[1]
        content = b[4].strip().replace("\n", " ")
        print(f"Y: {y:.2f} | {content}")

def find_block_indexes(blocks, skip_footer_lines=2):
    header_idx = None
    footer_idx = None

    # Step 1: Find header line index
    for i, block in enumerate(blocks):
        text = block[4].replace("\n", " ").lower()
        header_hits = sum(1 for kw in HEADER_KEYWORDS if kw in text)
        if header_hits >= 2:
            header_idx = i
            print(f"✅ HEADER detected at Y={block[1]:.2f} | Line: {text}")
            break

    # Step 2: Find footer after header line
    if header_idx is not None:
        for j in range(header_idx + 1, len(blocks)):
            text = blocks[j][4].replace("\n", " ").lower()
            if any(kw in text for kw in FOOTER_KEYWORDS):
                # Ensure footer index is a few lines above actual match
                footer_idx = max(header_idx + 1, j - skip_footer_lines)
                print(f"✅ FOOTER detected at Y={blocks[j][1]:.2f} | Line: {text}")
                break

    return header_idx, footer_idx

# --- Main Logic ---
doc = fitz.open(r"C:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\Fashionova\B158_91060_20230815_V1916.pdf")
page = doc[0]
blocks = page.get_text("blocks")

# Sort blocks by Y-coordinate (top to bottom)
sorted_blocks = sorted(blocks, key=lambda b: b[1])

# Detect header/footer block indexes
header_idx, footer_idx = find_block_indexes(sorted_blocks)

if header_idx is None or footer_idx is None:
    raise ValueError("❌ Could not detect both header and footer lines. Adjust keyword lists or debug block content.")

# Define areas
top_area = sorted_blocks[:header_idx]
line_items_area = sorted_blocks[header_idx:footer_idx]
bottom_area = sorted_blocks[footer_idx:]

# Output areas
print_blocks("Top Area", top_area)
print_blocks("Line Items Area", line_items_area)
print_blocks("Bottom Area", bottom_area)

✅ HEADER detected at Y=259.72 | Line: no. no. pegno. pegno. type no. type no. size size colour colour description description q'ty q'ty unit unit
✅ FOOTER detected at Y=259.72 | Line: excl.gst gst gst

=== TOP AREA ===
Y: 113.34 | Bill  To   :   CW Management Pty Ltd B655 Customer No. : PH1871
Y: 132.42 | Ship  To : Chemist Warehouse Townsville B158 Invoice No. : 91060
Y: 148.74 | Invoice Date : 15.08.23 126-128 Sturt St TOWNSVILLE QLD 4810 AUSTRALIA
Y: 157.39 | Address : Due Date : 30.09.23
Y: 181.26 | Invoice Amount : $ 187.25 AUD
Y: 228.72 | TAX INVOICE TAX INVOICE Page Page 11 of of 11
Y: 252.87 | Unit
Y: 252.87 | Unit
Y: 252.87 | Total
Y: 252.87 | Total
Y: 252.87 | Total
Y: 252.87 | Total

=== LINE ITEMS AREA ===
Y: 259.72 | No. No. PegNo. PegNo. Type No. Type No. Size Size Colour Colour Description Description Q'ty Q'ty Unit Unit

=== BOTTOM AREA ===
Y: 259.72 | excl.GST GST GST
Y: 265.36 | Price
Y: 265.36 | Price
Y: 265.36 | excl.GST
Y: 265.36 | Incl.GST
Y: 265.36 | Incl.GST
Y: 279.88 | 1 D08 D08 TN1-012L-C1 TN1-012L-C1 3-9 3-9 N.PK/OR/YL N.PK/OR/YLLadies' Casual Low cut Ladies' Casual Low cut 1 Dz Dz $42.78 $42.78 $42.78 $42.78 $4.28 $4.28 $47.06 $47.06
Y: 291.28 | 2 D12 D12 TN2-002M-B1 TN2-002M-B1 7-11 7-11 WH WH Men's Casual Anklet Men's Casual Anklet 1 Dz Dz $42.78 $42.78 $42.78 $42.78 $4.28 $4.28 $47.06 $47.06
Y: 302.80 | 3 PD03 PD03 BU4-002K-C2 BU4-002K-C2 11-14 11-14 BK BK Men's Business Diabetic Friendly  Extra Large Men's Business Diabetic Friendly  Extra Large 1 Dz Dz $64.17 $64.17 $64.17 $64.17 $6.42 $6.42 $70.59 $70.59
Y: 314.32 | 4 COU COU COU COU Courier Fee Courier Fee 1 Box Box $20.50 $20.50 $20.50 $20.50 $2.05 $2.05 $22.55 $22.55
Y: 328.72 | Total Q'ty 3 Dz $170.23 $17.02 $187.25 SATCHEL*1
Y: 412.15 | Total (GST Incl.) $187.25 RE-ORDERS & GENERAL ENQUIRIES
Y: 428.18 | - Please fax through Re-Order Form to 02 9748 6211 Due Date 30.09.23 o RE-ORDERS
Y: 444.66 | Last Balance $0.00 for your next order. New Re-Order Forms are supplied with this delivery.
Y: 462.88 | Current Payment $0.00 - Please contact FASHIONOVA at 029748 6222 o ENQUIRIES
Y: 478.94 | Leave your general enquiry on  www.soxnlox.com or e-mail to  info@fashionova.com.au Total Balance $187.25
Y: 510.50 | o All display stands will remain the property of Fashionova Pty Ltd.
Y: 587.11 | How to pay this invoice Fashionova Pty Ltd ABN : 96 125 037 434
Y: 617.13 | Electronic Funds Transfer Cheque in the Mail Credit Card Payment For Visa & Mastercard payments, please complete the following and mail or fax back to 02 9748 6211:
Y: 633.12 | Preferred Method of Payment Please make your cheque payable
Y: 647.73 | to Fashionova Pty Ltd Account ......: Fashionova Pty Ltd Bank ...........: CBA BSB/Acc No : 062 256/1042 5214
Y: 657.00 | Visa ____  Mastercard ____  Expiry:_______/_______
Y: 664.68 | (T/A SOX & LOX)
Y: 680.04 | Name on card: _______________________________
Y: 684.12 | Unit 3 / 10-11 Millennium Court Silverwater NSW 2128
Y: 684.84 | * Please quote  your Customer NO .: Or Invoice NO : for the payment.
Y: 699.36 | PH1871 91060
Y: 702.96 | Card#: ______________________________________
Y: 723.15 | Please note: 1.88% credit card surcharge applies.
Y: 827.49 | Page 1 1 of

In [7]:
line_items_area

[{'text': 'TTAAXX',
  'x0': 265.91870223711,
  'x1': 289.42895464751683,
  'top': 230.82727132313926,
  'doctop': 230.82727132313926,
  'bottom': 245.19341757624534,
  'upright': True,
  'height': 14.36614625310608,
  'width': 23.51025241040685,
  'direction': 'ltr'},
 {'text': 'IINNVVOOIICCEE',
  'x0': 292.79166801184147,
  'x1': 341.3067121056883,
  'top': 230.82727132313926,
  'doctop': 230.82727132313926,
  'bottom': 245.19341757624534,
  'upright': True,
  'height': 14.36614625310608,
  'width': 48.515044093846825,
  'direction': 'ltr'},
 {'text': 'PPaaggee',
  'x0': 494.1621748842923,
  'x1': 516.4463292063314,
  'top': 237.60521835638053,
  'doctop': 237.60521835638053,
  'bottom': 247.1827311117828,
  'upright': True,
  'height': 9.577512755402267,
  'width': 22.284154322039058,
  'direction': 'ltr'},
 {'text': '11',
  'x0': 530.2789155432353,
  'x1': 535.6072529570099,
  'top': 237.60521835638053,
  'doctop': 237.60521835638053,
  'bottom': 247.1827311117828,
  'upright': True,
  'height': 9.577512755402267,
  'width': 5.328337413774648,
  'direction': 'ltr'},
 {'text': 'ooff',
  'x0': 543.9590362499999,
  'x1': 551.902017995876,
  'top': 237.60521835638053,
  'doctop': 237.60521835638053,
  'bottom': 247.1827311117828,
  'upright': True,
  'height': 9.577512755402267,
  'width': 7.942981745876068,
  'direction': 'ltr'},
 {'text': '11',
  'x0': 560.8786099907077,
  'x1': 566.243190572039,
  'top': 237.60521835638053,
  'doctop': 237.60521835638053,
  'bottom': 247.1827311117828,
  'upright': True,
  'height': 9.577512755402267,
  'width': 5.3645805813313245,
  'direction': 'ltr'},
 {'text': 'UUnniitt',
  'x0': 442.19252205470553,
  'x1': 454.4706845111357,
  'top': 253.98886099085144,
  'doctop': 253.98886099085144,
  'bottom': 261.65092034717213,
  'upright': True,
  'height': 7.662059356320697,
  'width': 12.278162456430152,
  'direction': 'ltr'},
 {'text': 'TToottaall',
  'x0': 478.19366786719957,
  'x1': 493.12366815754035,
  'top': 253.98886099085144,
  'doctop': 253.98886099085144,
  'bottom': 261.65092034717213,
  'upright': True,
  'height': 7.662059356320697,
  'width': 14.930000290340786,
  'direction': 'ltr'},
 {'text': 'TToottaall',
  'x0': 547.1950226952945,
  'x1': 562.1250229856353,
  'top': 253.98886099085144,
  'doctop': 253.98886099085144,
  'bottom': 261.65092034717213,
  'upright': True,
  'height': 7.662059356320697,
  'width': 14.930000290340786,
  'direction': 'ltr'},
 {'text': 'NNoo..',
  'x0': 21.120990101694,
  'x1': 33.74803885339114,
  'top': 261.1138781912815,
  'doctop': 261.1138781912815,
  'bottom': 270.69139094668367,
  'upright': True,
  'height': 9.577512755402154,
  'width': 12.627048751697135,
  'direction': 'ltr'},
 {'text': 'PPeeggNNoo..',
  'x0': 42.12035227855875,
  'x1': 69.11809384326475,
  'top': 261.1138781912815,
  'doctop': 261.1138781912815,
  'bottom': 270.69139094668367,
  'upright': True,
  'height': 9.577512755402154,
  'width': 26.997741564705997,
  'direction': 'ltr'},
 {'text': 'TTyyppee',
  'x0': 87.838056908133,
  'x1': 106.09841724252962,
  'top': 261.1138781912815,
  'doctop': 261.1138781912815,
  'bottom': 270.69139094668367,
  'upright': True,
  'height': 9.577512755402154,
  'width': 18.260360334396623,
  'direction': 'ltr'},
 {'text': 'NNoo..',
  'x0': 108.2444407026056,
  'x1': 120.87148945430273,
  'top': 261.1138781912815,
  'doctop': 261.1138781912815,
  'bottom': 270.69139094668367,
  'upright': True,
  'height': 9.577512755402154,
  'width': 12.627048751697131,
  'direction': 'ltr'},
 {'text': 'SSiizzee',
  'x0': 145.3208245347495,
  'x1': 161.0902647815579,
  'top': 261.1138781912815,
  'doctop': 261.1138781912815,
  'bottom': 270.69139094668367,
  'upright': True,
  'height': 9.577512755402154,
  'width': 15.769440246808387,
  'direction': 'ltr'},
 {'text': 'CCoolloouurr',
  'x0': 179.881595295255,
  'x1': 205.15485372239993,
  'top': 261.1138781912815,
  'doctop': 261.1138781912815,
  'bottom': 270.69139094668367,
  'upright': True,
  'height': 9.577512755402154,
  'width': 25.273258427144924,
  'direction': 'ltr'},
 {'text': 'DDeessccrriippttiioonn',
  'x0': 275.4008474077297,
  'x1': 318.51292584675633,
  'top': 261.1138781912815,
  'doctop': 261.1138781912815,
  'bottom': 270.69139094668367,
  'upright': True,
  'height': 9.577512755402154,
  'width': 43.11207843902662,
  'direction': 'ltr'},
 {'text': "QQ''ttyy",
  'x0': 388.0777255817647,
  'x1': 403.080728878546,
  'top': 261.1138781912815,
  'doctop': 261.1138781912815,
  'bottom': 270.69139094668367,
  'upright': True,
  'height': 9.577512755402154,
  'width': 15.003003296781287,
  'direction': 'ltr'},
 {'text': 'UUnniitt',
  'x0': 412.91768175,
  'x1': 428.1697770555401,
  'top': 261.1138781912815,
  'doctop': 261.1138781912815,
  'bottom': 270.69139094668367,
  'upright': True,
  'height': 9.577512755402154,
  'width': 15.252095305540138,
  'direction': 'ltr'},
 {'text': 'GGSSTT',
  'x0': 512.0407532592923,
  'x1': 528.2317338286157,
  'top': 261.1138781912815,
  'doctop': 261.1138781912815,
  'bottom': 270.69139094668367,
  'upright': True,
  'height': 9.577512755402154,
  'width': 16.190980569323415,
  'direction': 'ltr'},
 {'text': 'PPrriiccee',
  'x0': 440.6347905,
  'x1': 456.0093185197246,
  'top': 266.4705912261619,
  'doctop': 266.4705912261619,
  'bottom': 274.1326505824826,
  'upright': True,
  'height': 7.662059356320697,
  'width': 15.374528019724607,
  'direction': 'ltr'},
 {'text': 'eexxccll..GGSSTT',
  'x0': 472.1942611171996,
  'x1': 499.1724957280823,
  'top': 266.4705912261619,
  'doctop': 266.4705912261619,
  'bottom': 274.1326505824826,
  'upright': True,
  'height': 7.662059356320697,
  'width': 26.978234610882737,
  'direction': 'ltr'},
 {'text': 'IInnccll..GGSSTT',
  'x0': 541.9136553047056,
  'x1': 567.5889638122219,
  'top': 266.4705912261619,
  'doctop': 266.4705912261619,
  'bottom': 274.1326505824826,
  'upright': True,
  'height': 7.662059356320697,
  'width': 25.67530850751632,
  'direction': 'ltr'},
 {'text': '11',
  'x0': 21.118363147372495,
  'x1': 25.91246726255938,
  'top': 281.6808708164748,
  'doctop': 281.6808708164748,
  'bottom': 290.3006568723364,
  'upright': True,
  'height': 8.619786055861596,
  'width': 4.794104115186887,
  'direction': 'ltr'},
 {'text': 'DD0088',
  'x0': 41.1613690459335,
  'x1': 55.49374001144101,
  'top': 281.2743490426428,
  'doctop': 281.2743490426428,
  'bottom': 290.851861798045,
  'upright': True,
  'height': 9.577512755402154,
  'width': 14.332370965507515,
  'direction': 'ltr'},
 {'text': 'TTNN11--001122LL--CC11',
  'x0': 85.31970042125249,
  'x1': 128.48388243676607,
  'top': 281.911646495442,
  'doctop': 281.911646495442,
  'bottom': 290.5314325513035,
  'upright': True,
  'height': 8.619786055861482,
  'width': 43.164182015513575,
  'direction': 'ltr'},
 {'text': '33--99',
  'x0': 145.68103660600875,
  'x1': 157.0434643901611,
  'top': 281.2743490426428,
  'doctop': 281.2743490426428,
  'bottom': 290.851861798045,
  'upright': True,
  'height': 9.577512755402154,
  'width': 11.362427784152345,
  'direction': 'ltr'},
 {'text': "NN..PPKK//OORR//YYLLLLaaddiieess''",
  'x0': 180.12077947870873,
  'x1': 242.89715725473695,
  'top': 281.2743490426428,
  'doctop': 281.2743490426428,
  'bottom': 290.851861798045,
  'upright': True,
  'height': 9.577512755402154,
  'width': 62.77637777602823,
  'direction': 'ltr'},
 {'text': 'CCaassuuaall',
  'x0': 245.129404871691,
  'x1': 269.48293895880335,
  'top': 281.2743490426428,
  'doctop': 281.2743490426428,
  'bottom': 290.851861798045,
  'upright': True,
  'height': 9.577512755402154,
  'width': 24.353534087112337,
  'direction': 'ltr'},
 {'text': 'LLooww',
  'x0': 271.6672842663807,
  'x1': 285.95175292251156,
  'top': 281.2743490426428,
  'doctop': 281.2743490426428,
  'bottom': 290.851861798045,
  'upright': True,
  'height': 9.577512755402154,
  'width': 14.284468656130855,
  'direction': 'ltr'},
 {'text': 'ccuutt',
  'x0': 288.14567869196424,
  'x1': 298.56922121233333,
  'top': 281.2743490426428,
  'doctop': 281.2743490426428,
  'bottom': 290.851861798045,
  'upright': True,
  'height': 9.577512755402154,
  'width': 10.423542520369097,
  'direction': 'ltr'},
 {'text': '11',
  'x0': 397.31669658176475,
  'x1': 401.68538719691946,
  'top': 281.2743490426428,
  'doctop': 281.2743490426428,
  'bottom': 290.851861798045,
  'upright': True,
  'height': 9.577512755402154,
  'width': 4.368690615154719,
  'direction': 'ltr'},
 {'text': 'DDzz',
  'x0': 415.80046316823524,
  'x1': 425.3809250435745,
  'top': 281.2743490426428,
  'doctop': 281.2743490426428,
  'bottom': 290.851861798045,
  'upright': True,
  'height': 9.577512755402154,
  'width': 9.580461875339267,
  'direction': 'ltr'},
 {'text': '$$4422..7788',
  'x0': 438.96221834873626,
  'x1': 462.7792465708296,
  'top': 281.2743490426428,
  'doctop': 281.2743490426428,
  'bottom': 290.851861798045,
  'upright': True,
  'height': 9.577512755402154,
  'width': 23.81702822209337,
  'direction': 'ltr'},
 {'text': '$$4422..7788',
  'x0': 473.52064784873625,
  'x1': 497.3376760708296,
  'top': 281.2743490426428,
  'doctop': 281.2743490426428,
  'bottom': 290.851861798045,
  'upright': True,
  'height': 9.577512755402154,
  'width': 23.81702822209337,
  'direction': 'ltr'},
 {'text': '$$44..2288',
  'x0': 511.3185589182353,
  'x1': 530.8243792964261,
  'top': 281.2743490426428,
  'doctop': 281.2743490426428,
  'bottom': 290.851861798045,
  'upright': True,
  'height': 9.577512755402154,
  'width': 19.505820378190776,
  'direction': 'ltr'},
 {'text': '$$4477..0066',
  'x0': 545.2805371157077,
  'x1': 569.0975653378011,
  'top': 281.2743490426428,
  'doctop': 281.2743490426428,
  'bottom': 290.851861798045,
  'upright': True,
  'height': 9.577512755402154,
  'width': 23.817028222093427,
  'direction': 'ltr'},
 {'text': '22',
  'x0': 21.118363147372495,
  'x1': 25.91246726255938,
  'top': 293.08168480192535,
  'doctop': 293.08168480192535,
  'bottom': 301.70147085778694,
  'upright': True,
  'height': 8.619786055861596,
  'width': 4.794104115186887,
  'direction': 'ltr'},
 {'text': 'DD1122',
  'x0': 41.1613690459335,
  'x1': 55.49374001144101,
  'top': 292.67510769872354,
  'doctop': 292.67510769872354,
  'bottom': 302.2526204541257,
  'upright': True,
  'height': 9.577512755402154,
  'width': 14.332370965507515,
  'direction': 'ltr'},
 {'text': 'TTNN22--000022MM--BB11',
  'x0': 85.31970042125249,
  'x1': 129.94970563745272,
  'top': 293.31243478041904,
  'doctop': 293.31243478041904,
  'bottom': 301.9322208362805,
  'upright': True,
  'height': 8.619786055861482,
  'width': 44.63000521620023,
  'direction': 'ltr'},
 {'text': '77--1111',
  'x0': 145.68103660600875,
  'x1': 161.35467223406374,
  'top': 292.67510769872354,
  'doctop': 292.67510769872354,
  'bottom': 302.2526204541257,
  'upright': True,
  'height': 9.577512755402154,
  'width': 15.673635628054996,
  'direction': 'ltr'},
 {'text': 'WWHH',
  'x0': 180.12077947870873,
  'x1': 191.94221246777568,
  'top': 293.31243478041904,
  'doctop': 293.31243478041904,
  'bottom': 301.9322208362805,
  'upright': True,
  'height': 8.619786055861482,
  'width': 11.821432989066949,
  'direction': 'ltr'},
 {'text': "MMeenn''ss",
  'x0': 218.3999162394945,
  'x1': 239.09371389022726,
  'top': 292.67510769872354,
  'doctop': 292.67510769872354,
  'bottom': 302.2526204541257,
  'upright': True,
  'height': 9.577512755402154,
  'width': 20.693797650732762,
  'direction': 'ltr'},
 {'text': 'CCaassuuaall',
  'x0': 241.2972201215553,
  'x1': 265.65075420866765,
  'top': 292.67510769872354,
  'doctop': 292.67510769872354,
  'bottom': 302.2526204541257,
  'upright': True,
  'height': 9.577512755402154,
  'width': 24.353534087112337,
  'direction': 'ltr'},
 {'text': 'AAnnkklleett',
  'x0': 267.835099516245,
  'x1': 289.65939166826786,
  'top': 292.67510769872354,
  'doctop': 292.67510769872354,
  'bottom': 302.2526204541257,
  'upright': True,
  'height': 9.577512755402154,
  'width': 21.82429215202285,
  'direction': 'ltr'},
 {'text': '11',
  'x0': 397.31669658176475,
  'x1': 401.68538719691946,
  'top': 292.67510769872354,
  'doctop': 292.67510769872354,
  'bottom': 302.2526204541257,
  'upright': True,
  'height': 9.577512755402154,
  'width': 4.368690615154719,
  'direction': 'ltr'},
 {'text': 'DDzz',
  'x0': 415.80046316823524,
  'x1': 425.3809250435745,
  'top': 292.67510769872354,
  'doctop': 292.67510769872354,
  'bottom': 302.2526204541257,
  'upright': True,
  'height': 9.577512755402154,
  'width': 9.580461875339267,
  'direction': 'ltr'},
 {'text': '$$4422..7788',
  'x0': 438.96221834873626,
  'x1': 462.7792465708296,
  'top': 292.67510769872354,
  'doctop': 292.67510769872354,
  'bottom': 302.2526204541257,
  'upright': True,
  'height': 9.577512755402154,
  'width': 23.81702822209337,
  'direction': 'ltr'},
 {'text': '$$4422..7788',
  'x0': 473.52064784873625,
  'x1': 497.3376760708296,
  'top': 292.67510769872354,
  'doctop': 292.67510769872354,
  'bottom': 302.2526204541257,
  'upright': True,
  'height': 9.577512755402154,
  'width': 23.81702822209337,
  'direction': 'ltr'},
 {'text': '$$44..2288',
  'x0': 511.3185589182353,
  'x1': 530.8243792964261,
  'top': 292.67510769872354,
  'doctop': 292.67510769872354,
  'bottom': 302.2526204541257,
  'upright': True,
  'height': 9.577512755402154,
  'width': 19.505820378190776,
  'direction': 'ltr'},
 {'text': '$$4477..0066',
  'x0': 545.2805371157077,
  'x1': 569.0975653378011,
  'top': 292.67510769872354,
  'doctop': 292.67510769872354,
  'bottom': 302.2526204541257,
  'upright': True,
  'height': 9.577512755402154,
  'width': 23.817028222093427,
  'direction': 'ltr'},
 {'text': '33',
  'x0': 21.118363147372495,
  'x1': 25.91246726255938,
  'top': 304.6008735373757,
  'doctop': 304.6008735373757,
  'bottom': 313.2206595932373,
  'upright': True,
  'height': 8.619786055861596,
  'width': 4.794104115186887,
  'direction': 'ltr'},
 {'text': 'PPDD0033',
  'x0': 41.1613690459335,
  'x1': 60.7629940428776,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 19.601624996944103,
  'direction': 'ltr'},
 {'text': 'BBUU44--000022KK--CC22',
  'x0': 85.31970042125249,
  'x1': 129.60480606082055,
  'top': 304.8316235158695,
  'doctop': 304.8316235158695,
  'bottom': 313.451409571731,
  'upright': True,
  'height': 8.619786055861482,
  'width': 44.28510563956806,
  'direction': 'ltr'},
 {'text': '1111--1144',
  'x0': 145.68103660600875,
  'x1': 165.66588007796642,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 19.984843471957674,
  'direction': 'ltr'},
 {'text': 'BBKK',
  'x0': 180.12077947870873,
  'x1': 189.48480298427162,
  'top': 304.8316235158695,
  'doctop': 304.8316235158695,
  'bottom': 313.451409571731,
  'upright': True,
  'height': 8.619786055861482,
  'width': 9.364023505562898,
  'direction': 'ltr'},
 {'text': "MMeenn''ss",
  'x0': 218.3999162394945,
  'x1': 239.09371389022726,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 20.693797650732762,
  'direction': 'ltr'},
 {'text': 'BBuussiinneessss',
  'x0': 241.2972201215553,
  'x1': 273.200158166435,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 31.902938044879704,
  'direction': 'ltr'},
 {'text': 'DDiiaabbeettiicc',
  'x0': 275.40366439776307,
  'x1': 303.6660269300138,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 28.262362532250734,
  'direction': 'ltr'},
 {'text': 'FFrriieennddllyy',
  'x0': 305.86953316134185,
  'x1': 333.8444818373324,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 27.97494867599056,
  'direction': 'ltr'},
 {'text': 'EExxttrraa',
  'x0': 338.1556896812351,
  'x1': 356.60765925313854,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 18.45196957190342,
  'direction': 'ltr'},
 {'text': 'LLaarrggee',
  'x0': 358.6578780944611,
  'x1': 378.64272156641886,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 19.98484347195773,
  'direction': 'ltr'},
 {'text': '11',
  'x0': 397.31669658176475,
  'x1': 401.68538719691946,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 4.368690615154719,
  'direction': 'ltr'},
 {'text': 'DDzz',
  'x0': 415.80046316823524,
  'x1': 425.3809250435745,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 9.580461875339267,
  'direction': 'ltr'},
 {'text': '$$6644..1177',
  'x0': 438.96221834873626,
  'x1': 462.7792465708296,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 23.81702822209337,
  'direction': 'ltr'},
 {'text': '$$6644..1177',
  'x0': 473.52064784873625,
  'x1': 497.3376760708296,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 23.81702822209337,
  'direction': 'ltr'},
 {'text': '$$66..4422',
  'x0': 511.3185589182353,
  'x1': 530.8243792964261,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 19.505820378190776,
  'direction': 'ltr'},
 {'text': '$$7700..5599',
  'x0': 545.2805371157077,
  'x1': 569.0975653378011,
  'top': 304.19397815147795,
  'doctop': 304.19397815147795,
  'bottom': 313.7714909068801,
  'upright': True,
  'height': 9.577512755402154,
  'width': 23.817028222093427,
  'direction': 'ltr'},
 {'text': '44',
  'x0': 21.118363147372495,
  'x1': 25.91246726255938,
  'top': 316.1200365723528,
  'doctop': 316.1200365723528,
  'bottom': 324.73982262821437,
  'upright': True,
  'height': 8.619786055861596,
  'width': 4.794104115186887,
  'direction': 'ltr'},
 {'text': 'CCOOUU',
  'x0': 41.1613690459335,
  'x1': 58.607390120926276,
  'top': 315.71573144498655,
  'doctop': 315.71573144498655,
  'bottom': 325.2932442003887,
  'upright': True,
  'height': 9.577512755402154,
  'width': 17.446021074992778,
  'direction': 'ltr'},
 {'text': 'CCOOUU',
  'x0': 85.31970042125249,
  'x1': 101.10747854158916,
  'top': 316.3534325158695,
  'doctop': 316.3534325158695,
  'bottom': 324.97321857173097,
  'upright': True,
  'height': 8.619786055861482,
  'width': 15.787778120336668,
  'direction': 'ltr'},
 {'text': 'CCoouurriieerr',
  'x0': 218.3999162394945,
  'x1': 243.99891037040098,
  'top': 315.71573144498655,
  'doctop': 315.71573144498655,
  'bottom': 325.2932442003887,
  'upright': True,
  'height': 9.577512755402154,
  'width': 25.598994130906476,
  'direction': 'ltr'},
 {'text': 'FFeeee',
  'x0': 246.27906029673173,
  'x1': 259.74918969345873,
  'top': 315.71573144498655,
  'doctop': 315.71573144498655,
  'bottom': 325.2932442003887,
  'upright': True,
  'height': 9.577512755402154,
  'width': 13.470129396727003,
  'direction': 'ltr'},
 {'text': '11',
  'x0': 397.31669658176475,
  'x1': 401.68538719691946,
  'top': 315.71573144498655,
  'doctop': 315.71573144498655,
  'bottom': 325.2932442003887,
  'upright': True,
  'height': 9.577512755402154,
  'width': 4.368690615154719,
  'direction': 'ltr'},
 {'text': 'BBooxx',
  'x0': 413.75970884873624,
  'x1': 427.2681600929646,

In [5]:
print(bottom_area)

[{'text': 'SATCHEL*1', 'x0': 23.997934449153, 'x1': 68.60456494073256, 'top': 332.04346378923333, 'doctop': 332.04346378923333, 'bottom': 341.6209765446356, 'upright': True, 'height': 9.577512755402267, 'width': 44.60663049157956, 'direction': 'ltr'}, {'text': 'Total', 'x0': 320.03679165126374, 'x1': 341.3245779382675, 'top': 330.60833958647885, 'doctop': 330.60833958647885, 'bottom': 340.1858523418811, 'upright': True, 'height': 9.577512755402267, 'width': 21.28778628700377, 'direction': 'ltr'}, {'text': "Q'ty", 'x0': 344.0837509583653, 'x1': 360.7537546214555, 'top': 330.60833958647885, 'doctop': 330.60833958647885, 'bottom': 340.1858523418811, 'upright': True, 'height': 9.577512755402267, 'width': 16.670003663090256, 'direction': 'ltr'}, {'text': '3', 'x0': 399.00075075, 'x1': 404.32748755268864, 'top': 330.60833958647885, 'doctop': 330.60833958647885, 'bottom': 340.1858523418811, 'upright': True, 'height': 9.577512755402267, 'width': 5.326736802688629, 'direction': 'ltr'}, {'text': 'RE-ORDERS', 'x0': 25.920576301525497, 'x1': 83.55663494356642, 'top': 415.20659778549634, 'doctop': 415.20659778549634, 'bottom': 424.7841105408986, 'upright': True, 'height': 9.577512755402267, 'width': 57.63605864204092, 'direction': 'ltr'}, {'text': '&', 'x0': 86.18168149740937, 'x1': 93.09877497140431, 'top': 415.20659778549634, 'doctop': 415.20659778549634, 'bottom': 424.7841105408986, 'upright': True, 'height': 9.577512755402267, 'width': 6.917093473994939, 'direction': 'ltr'}, {'text': 'GENERAL', 'x0': 95.76214337274862, 'x1': 142.32318808689735, 'top': 415.20659778549634, 'doctop': 415.20659778549634, 'bottom': 424.7841105408986, 'upright': True, 'height': 9.577512755402267, 'width': 46.56104471414872, 'direction': 'ltr'}, {'text': 'ENQUIRIES', 'x0': 145.00571741199235, 'x1': 197.65993587885683, 'top': 415.20659778549634, 'doctop': 415.20659778549634, 'bottom': 424.7841105408986, 'upright': True, 'height': 9.577512755402267, 'width': 52.65421846686448, 'direction': 'ltr'}, {'text': 'Total', 'x0': 390.8367178751468, 'x1': 416.09734497584157, 'top': 413.37056903949497, 'doctop': 413.37056903949497, 'bottom': 423.90580849443796, 'upright': True, 'height': 10.535239454942996, 'width': 25.260627100694762, 'direction': 'ltr'}, {'text': '(GST', 'x0': 418.8689532059136, 'x1': 444.0558112662643, 'top': 413.37056903949497, 'doctop': 413.37056903949497, 'bottom': 423.90580849443796, 'upright': True, 'height': 10.535239454942996, 'width': 25.186858060350687, 'direction': 'ltr'}, {'text': 'Incl.)', 'x0': 447.00657288002924, 'x1': 471.4873558399433, 'top': 413.37056903949497, 'doctop': 413.37056903949497, 'bottom': 423.90580849443796, 'upright': True, 'height': 10.535239454942996, 'width': 24.480782959914052, 'direction': 'ltr'}, {'text': '$187.25', 'x0': 532.7974719074542, 'x1': 570.9044504623613, 'top': 413.37056903949497, 'doctop': 413.37056903949497, 'bottom': 423.90580849443796, 'upright': True, 'height': 10.535239454942996, 'width': 38.10697855490707, 'direction': 'ltr'}, {'text': 'o', 'x0': 25.920576301525497, 'x1': 31.831721278609812, 'top': 430.15571389770184, 'doctop': 430.15571389770184, 'bottom': 439.7332266531041, 'upright': True, 'height': 9.577512755402267, 'width': 5.911144977084316, 'direction': 'ltr'}, {'text': 'RE-ORDERS', 'x0': 34.54299198933082, 'x1': 92.15030924574573, 'top': 430.15571389770184, 'doctop': 430.15571389770184, 'bottom': 439.7332266531041, 'upright': True, 'height': 9.577512755402267, 'width': 57.60731725641491, 'direction': 'ltr'}, {'text': '-', 'x0': 105.361691091867, 'x1': 108.83939875261515, 'top': 432.0760156222106, 'doctop': 432.0760156222106, 'bottom': 441.6535283776129, 'upright': True, 'height': 9.577512755402267, 'width': 3.477707660748152, 'direction': 'ltr'}, {'text': 'Please', 'x0': 111.87640516709769, 'x1': 138.75918118929962, 'top': 432.0760156222106, 'doctop': 432.0760156222106, 'bottom': 441.6535283776129, 'upright': True, 'height': 9.577512755402267, 'width': 26.882776022201938, 'direction': 'ltr'}, {'text': 'fax', 'x0': 141.67164159940276, 'x1': 154.46155820298068, 'top': 432.0760156222106, 'doctop': 432.0760156222106, 'bottom': 441.6535283776129, 'upright': True, 'height': 9.577512755402267, 'width': 12.789916603577922, 'direction': 'ltr'}, {'text': 'through', 'x0': 157.57520831246592, 'x1': 190.8864742530205, 'top': 432.0760156222106, 'doctop': 432.0760156222106, 'bottom': 441.6535283776129, 'upright': True, 'height': 9.577512755402267, 'width': 33.31126594055459, 'direction': 'ltr'}, {'text': 'Re-Order', 'x0': 193.88515882000166, 'x1': 232.49442017761885, 'top': 432.0760156222106, 'doctop': 432.0760156222106, 'bottom': 441.6535283776129, 'upright': True, 'height': 9.577512755402267, 'width': 38.609261357617186, 'direction': 'ltr'}, {'text': 'Form', 'x0': 235.56016797772742, 'x1': 257.2982359728722, 'top': 432.0760156222106, 'doctop': 432.0760156222106, 'bottom': 441.6535283776129, 'upright': True, 'height': 9.577512755402267, 'width': 21.738067995144775, 'direction': 'ltr'}, {'text': 'to', 'x0': 260.2777596161027, 'x1': 268.7277269901519, 'top': 432.0760156222106, 'doctop': 432.0760156222106, 'bottom': 441.6535283776129, 'upright': True, 'height': 9.577512755402267, 'width': 8.449967374049209, 'direction': 'ltr'}, {'text': '02', 'x0': 271.6785092477564, 'x1': 282.1691150012528, 'top': 432.0760156222106, 'doctop': 432.0760156222106, 'bottom': 441.6535283776129, 'upright': True, 'height': 9.577512755402267, 'width': 10.490605753496425, 'direction': 'ltr'}, {'text': '9748', 'x0': 285.28276511073807, 'x1': 306.3118789271077, 'top': 432.0760156222106, 'doctop': 432.0760156222106, 'bottom': 441.6535283776129, 'upright': True, 'height': 9.577512755402267, 'width': 21.02911381636966, 'direction': 'ltr'}, {'text': '6211', 'x0': 309.3297244178396, 'x1': 330.45464285296265, 'top': 432.0760156222106, 'doctop': 432.0760156222106, 'bottom': 441.6535283776129, 'upright': True, 'height': 9.577512755402267, 'width': 21.12491843512305, 'direction': 'ltr'}, {'text': 'Due', 'x0': 390.8367178751468, 'x1': 410.81758937406937, 'top': 431.60982507004996, 'doctop': 431.60982507004996, 'bottom': 442.14506452499296, 'upright': True, 'height': 10.535239454942996, 'width': 19.980871498922568, 'direction': 'ltr'}, {'text': 'Date', 'x0': 413.705120381825, 'x1': 436.6367534945125, 'top': 431.60982507004996, 'doctop': 431.60982507004996, 'bottom': 442.14506452499296, 'upright': True, 'height': 10.535239454942996, 'width': 22.931633112687507, 'direction': 'ltr'}, {'text': '30.09.23', 'x0': 529.9158812501468, 'x1': 570.9736214188188, 'top': 430.648497599009, 'doctop': 430.648497599009, 'bottom': 441.183737053952, 'upright': True, 'height': 10.535239454942996, 'width': 41.05774016867201, 'direction': 'ltr'}, {'text': 'for', 'x0': 36.361784658811494, 'x1': 47.954143527971986, 'top': 448.27722889770183, 'doctop': 448.27722889770183, 'bottom': 457.8547416531041, 'upright': True, 'height': 9.577512755402267, 'width': 11.592358869160492, 'direction': 'ltr'}, {'text': 'your', 'x0': 51.01989132808055, 'x1': 69.79759660374549, 'top': 448.27722889770183, 'doctop': 448.27722889770183, 'bottom': 457.8547416531041, 'upright': True, 'height': 9.577512755402267, 'width': 18.777705275664943, 'direction': 'ltr'}, {'text': 'next', 'x0': 72.86334440385406, 'x1': 91.29615305200676, 'top': 448.27722889770183, 'doctop': 448.27722889770183, 'bottom': 457.8547416531041, 'upright': True, 'height': 9.577512755402267, 'width': 18.4328086481527, 'direction': 'ltr'}, {'text': 'order.', 'x0': 94.32357900461398, 'x1': 119.63515927926025, 'top': 448.27722889770183, 'doctop': 448.27722889770183, 'bottom': 457.8547416531041, 'upright': True, 'height': 9.577512755402267, 'width': 25.311580274646275, 'direction': 'ltr'}, {'text': 'New', 'x0': 122.68174615561816, 'x1': 141.1911984987736, 'top': 448.27722889770183, 'doctop': 448.27722889770183, 'bottom': 457.8547416531041, 'upright': True, 'height': 9.577512755402267, 'width': 18.50945234315543, 'direction': 'ltr'}, {'text': 'Re-Order', 'x0': 144.14198075637808, 'x1': 182.75124211399526, 'top': 448.27722889770183, 'doctop': 448.27722889770183, 'bottom': 457.8547416531041, 'upright': True, 'height': 9.577512755402267, 'width': 38.609261357617186, 'direction': 'ltr'}, {'text': 'Forms', 'x0': 185.7211852953504, 'x1': 211.74171974877183, 'top': 448.27722889770183, 'doctop': 448.27722889770183, 'bottom': 457.8547416531041, 'upright': True, 'height': 9.577512755402267, 'width': 26.02053445342142, 'direction': 'ltr'}, {'text': 'are', 'x0': 214.84578939638172, 'x1': 228.31591879310875, 'top': 448.27722889770183, 'doctop': 448.27722889770183, 'bottom': 457.8547416531041, 'upright': True, 'height': 9.577512755402267, 'width': 13.470129396727032, 'direction': 'ltr'}, {'text': 'supplied', 'x0': 231.32418382196525, 'x1': 266.3120305907041, 'top': 448.27722889770183, 'doctop': 448.27722889770183, 'bottom': 457.8547416531041, 'upright': True, 'height': 9.577512755402267, 'width': 34.987846768738876, 'direction': 'ltr'}, {'text': 'with', 'x0': 269.26281284830867, 'x1': 287.05373055081367, 'top': 448.27722889770183, 'doctop': 448.27722889770183, 'bottom': 457.8547416531041, 'upright': True, 'height': 9.577512755402267, 'width': 17.790917702505, 'direction': 'ltr'}, {'text': 'this', 'x0': 290.14821973654824, 'x1': 305.247027652083, 'top': 448.27722889770183, 'doctop': 448.27722889770183, 'bottom': 457.8547416531041, 'upright': True, 'height': 9.577512755402267, 'width': 15.098807915534735, 'direction': 'ltr'}, {'text': 'delivery.', 'x0': 308.2552926809395, 'x1': 343.91377178095223, 'top': 448.27722889770183, 'doctop': 448.27722889770183, 'bottom': 457.8547416531041, 'upright': True, 'height': 9.577512755402267, 'width': 35.658479100012755, 'direction': 'ltr'}, {'text': 'Last', 'x0': 390.8367178751468, 'x1': 412.57750790799344, 'top': 446.84939907004997, 'doctop': 446.84939907004997, 'bottom': 457.38463852499297, 'upright': True, 'height': 10.535239454942996, 'width': 21.740790032846633, 'direction': 'ltr'}, {'text': 'Balance', 'x0': 415.391269875405, 'x1': 456.027472670682, 'top': 446.84939907004997, 'doctop': 446.84939907004997, 'bottom': 457.38463852499297, 'upright': True, 'height': 10.535239454942996, 'width': 40.63620279527703, 'direction': 'ltr'}, {'text': '$0.00', 'x0': 544.5554923425458, 'x1': 570.964808785742, 'top': 445.88486907005, 'doctop': 445.88486907005, 'bottom': 456.420108524993, 'upright': True, 'height': 10.535239454942996, 'width': 26.40931644319619, 'direction': 'ltr'}, {'text': 'o', 'x0': 25.920576301525497, 'x1': 31.831721278609812, 'top': 465.5569759972106, 'doctop': 465.5569759972106, 'bottom': 475.13448875261287, 'upright': True, 'height': 9.577512755402267, 'width': 5.911144977084316, 'direction': 'ltr'}, {'text': 'ENQUIRIES', 'x0': 34.54299198933082, 'x1': 90.71323996444485, 'top': 465.5569759972106, 'doctop': 465.5569759972106, 'bottom': 475.13448875261287, 'upright': True, 'height': 9.577512755402267, 'width': 56.17024797511403, 'direction': 'ltr'}, {'text': '-', 'x0': 105.361691091867, 'x1': 108.83939875261515, 'top': 467.4772777217193, 'doctop': 467.4772777217193, 'bottom': 477.05479047712157, 'upright': True, 'height': 9.577512755402267, 'width': 3.477707660748152, 'direction': 'ltr'}, {'text': 'Please', 'x0': 111.87640516709769, 'x1': 138.75918118929962, 'top': 467.4772777217193, 'doctop': 467.4772777217193, 'bottom': 477.05479047712157, 'upright': True, 'height': 9.577512755402267, 'width': 26.882776022201938, 'direction': 'ltr'}, {'text': 'contact', 'x0': 141.67164159940276, 'x1': 172.65485530424988, 'top': 467.4772777217193, 'doctop': 467.4772777217193, 'bottom': 477.05479047712157, 'upright': True, 'height': 9.577512755402267, 'width': 30.983213704847117, 'direction': 'ltr'}, {'text': 'FASHIONOVA', 'x0': 175.6822812568571, 'x1': 233.53869052203083, 'top': 467.4772777217193, 'doctop': 467.4772777217193, 'bottom': 477.05479047712157, 'upright': True, 'height': 9.577512755402267, 'width': 57.85640926517374, 'direction': 'ltr'}, {'text': 'at', 'x0': 236.51821416526133, 'x1': 244.79573322555447, 'top': 467.4772777217193, 'doctop': 467.4772777217193, 'bottom': 477.05479047712157, 'upright': True, 'height': 9.577512755402267, 'width': 8.277519060293145, 'direction': 'ltr'}, {'text': '029748', 'x0': 247.82315917816163, 'x1': 279.3907810574044, 'top': 467.4772777217193, 'doctop': 467.4772777217193, 'bottom': 477.05479047712157, 'upright': True, 'height': 9.577512755402267, 'width': 31.56762187924278, 'direction': 'ltr'}, {'text': '6222', 'x0': 282.5044311668897, 'x1': 303.53354498325933, 'top': 467.4772777217193, 'doctop': 467.4772777217193, 'bottom': 477.05479047712157, 'upright': True, 'height': 9.577512755402267, 'width': 21.02911381636966, 'direction': 'ltr'}, {'text': 'Current', 'x0': 390.8367178751468, 'x1': 429.01746547039807, 'top': 464.1273590410909, 'doctop': 464.1273590410909, 'bottom': 474.6625984960339, 'upright': True, 'height': 10.535239454942996, 'width': 38.18074759525126, 'direction': 'ltr'}, {'text': 'Payment', 'x0': 431.83122743780956, 'x1': 475.7027295738932, 'top': 464.1273590410909, 'doctop': 464.1273590410909, 'bottom': 474.6625984960339, 'upright': True, 'height': 10.535239454942996, 'width': 43.87150213608362, 'direction': 'ltr'}, {'text': '$0.00', 'x0': 542.2842786584251, 'x1': 570.97992343422, 'top': 464.2137345429486, 'doctop': 464.2137345429486, 'bottom': 475.7067006974323, 'upright': True, 'height': 11.492966154483724, 'width': 28.695644775794904, 'direction': 'ltr'}, {'text': 'Leave', 'x0': 37.320764295255, 'x1': 62.00003408612891, 'top': 480.91933276896486, 'doctop': 480.91933276896486, 'bottom': 490.49684552436713, 'upright': True, 'height': 9.577512755402267, 'width': 24.67926979087391, 'direction': 'ltr'}, {'text': 'your', 'x0': 65.00829911498545, 'x1': 83.88180900940378, 'top': 480.91933276896486, 'doctop': 480.91933276896486, 'bottom': 490.49684552436713, 'upright': True, 'height': 9.577512755402267, 'width': 18.873509894418333, 'direction': 'ltr'}, {'text': 'general', 'x0': 86.85175219075894, 'x1': 118.3523108368744, 'top': 480.91933276896486, 'doctop': 480.91933276896486, 'bottom': 490.49684552436713, 'upright': True, 'height': 9.577512755402267, 'width': 31.50055864611545, 'direction': 'ltr'}, {'text': 'enquiry', 'x0': 121.34141494198025, 'x1': 152.8419735880957, 'top': 480.91933276896486, 'doctop': 480.91933276896486, 'bottom': 490.49684552436713, 'upright': True, 'height': 9.577512755402267, 'width': 31.50055864611545, 'direction': 'ltr'}, {'text': 'on', 'x0': 155.92688231195493, 'x1': 166.3408443704487, 'top': 480.91933276896486, 'doctop': 480.91933276896486, 'bottom': 490.49684552436713, 'upright': True, 'height': 9.577512755402267, 'width': 10.41396205849378, 'direction': 'ltr'}, {'text': 'www.soxnlox.com', 'x0': 172.40527673753843, 'x1': 248.84778204087038, 'top': 480.91933276896486, 'doctop': 480.91933276896486, 'bottom': 490.49684552436713, 'upright': True, 'height': 9.577512755402267, 'width': 76.44250530333196, 'direction': 'ltr'}, {'text': 'Total', 'x0': 390.83987615842506, 'x1': 418.1674192802458, 'top': 483.4130847397311, 'doctop': 483.4130847397311, 'bottom': 494.90605089421484, 'upright': True, 'height': 11.492966154483724, 'width': 27.327543121820725, 'direction': 'ltr'}, {'text': 'Balance', 'x0': 421.4209719531424, 'x1': 465.5221311518399, 'top': 483.4130847397311, 'doctop': 483.4130847397311, 'bottom': 494.90605089421484, 'upright': True, 'height': 11.492966154483724, 'width': 44.10115919869753, 'direction': 'ltr'}, {'text': '$187.25', 'x0': 529.5659661584251, 'x1': 571.0228952696095, 'top': 482.45208454294857, 'doctop': 482.45208454294857, 'bottom': 493.9450506974323, 'upright': True, 'height': 11.492966154483724, 'width': 41.45692911118442, 'direction': 'ltr'}, {'text': 'or', 'x0': 37.320764295255, 'x1': 45.94317998306033, 'top': 492.31543887221056, 'doctop': 492.31543887221056, 'bottom': 501.89295162761283, 'upright': True, 'height': 9.577512755402267, 'width': 8.62241568780533, 'direction': 'ltr'}, {'text': 'e-mail', 'x0': 48.913123164415495, 'x1': 74.85701392283418, 'top': 492.31543887221056, 'doctop': 492.31543887221056, 'bottom': 501.89295162761283, 'upright': True, 'height': 9.577512755402267, 'width': 25.94389075841869, 'direction': 'ltr'}, {'text': 'to', 'x0': 77.84611802794004, 'x1': 86.29608540198925, 'top': 492.31543887221056, 'doctop': 492.31543887221056, 'bottom': 501.89295162761283, 'upright': True, 'height': 9.577512755402267, 'width': 8.449967374049209, 'direction': 'ltr'}, {'text': 'info@fashionova.com.au', 'x0': 92.3126154597023, 'x1': 196.04027618400045, 'top': 492.31543887221056, 'doctop': 492.31543887221056, 'bottom': 501.89295162761283, 'upright': True, 'height': 9.577512755402267, 'width': 103.72766072429815, 'direction': 'ltr'}, {'text': 'o', 'x0': 25.920576301525497, 'x1': 31.113186637959373, 'top': 512.4771085494739, 'doctop': 512.4771085494739, 'bottom': 522.0546213048762, 'upright': True, 'height': 9.577512755402267, 'width': 5.1926103364338765, 'direction': 'ltr'}, {'text': 'All', 'x0': 34.06396889556386, 'x1': 44.20009755967279, 'top': 512.4771085494739, 'doctop': 512.4771085494739, 'bottom': 522.0546213048762, 'upright': True, 'height': 9.577512755402267, 'width': 10.13612866410893, 'direction': 'ltr'}, {'text': 'display', 'x0': 47.189201664778636, 'x1': 76.19884022330588, 'top': 512.4771085494739, 'doctop': 512.4771085494739, 'bottom': 522.0546213048762, 'upright': True, 'height': 9.577512755402267, 'width': 29.009638558527243, 'direction': 'ltr'}, {'text': 'stands', 'x0': 79.18794432841173, 'x1': 106.74135268188742, 'top': 512.4771085494739, 'doctop': 512.4771085494739, 'bottom': 522.0546213048762, 'upright': True, 'height': 9.577512755402267, 'width': 27.55340835347569, 'direction': 'ltr'}, {'text': 'will', 'x0': 109.84542232949732, 'x1': 123.4305172687284, 'top': 512.4771085494739, 'doctop': 512.4771085494739, 'bottom': 522.0546213048762, 'upright': True, 'height': 9.577512755402267, 'width': 13.58509493923107, 'direction': 'ltr'}, {'text': 'remain', 'x0': 126.32381675508086, 'x1': 155.41967947048616, 'top': 512.4771085494739, 'doctop': 512.4771085494739, 'bottom': 522.0546213048762, 'upright': True, 'height': 9.577512755402267, 'width': 29.095862715405303, 'direction': 'ltr'}, {'text': 'the', 'x0': 158.51416865622076, 'x1': 172.1759072904545, 'top': 512.4771085494739, 'doctop': 512.4771085494739, 'bottom': 522.0546213048762, 'upright': True, 'height': 9.577512755402267, 'width': 13.661738634233728, 'direction': 'ltr'}, {'text': 'property', 'x0': 175.18417231931102, 'x1': 210.90013419057576, 'top': 512.4771085494739, 'doctop': 512.4771085494739, 'bottom': 522.0546213048762, 'upright': True, 'height': 9.577512755402267, 'width': 35.71596187126474, 'direction': 'ltr'}, {'text': 'of', 'x0': 213.98504291443496, 'x1': 222.20507920347606, 'top': 512.4771085494739, 'doctop': 512.4771085494739, 'bottom': 522.0546213048762, 'upright': True, 'height': 9.577512755402267, 'width': 8.220036289041104, 'direction': 'ltr'}, {'text': 'Fashionova', 'x0': 225.09837868982854, 'x1': 272.65579143901266, 'top': 512.4771085494739, 'doctop': 512.4771085494739, 'bottom': 522.0546213048762, 'upright': True, 'height': 9.577512755402267, 'width': 47.557412749184124, 'direction': 'ltr'}, {'text': 'Pty', 'x0': 275.68321739161985, 'x1': 288.8850938558374, 'top': 512.4771085494739, 'doctop': 512.4771085494739, 'bottom': 522.0546213048762, 'upright': True, 'height': 9.577512755402267, 'width': 13.201876464217548, 'direction': 'ltr'}, {'text': 'Ltd.', 'x0': 291.9700025796966, 'x1': 308.18014407277064, 'top': 512.4771085494739, 'doctop': 512.4771085494739, 'bottom': 522.0546213048762, 'upright': True, 'height': 9.577512755402267, 'width': 16.210141493074048, 'direction': 'ltr'}, {'text': 'How', 'x0': 25.917990182535004, 'x1': 54.00431237294642, 'top': 591.8194813872517, 'doctop': 591.8194813872517, 'bottom': 603.3124475417355, 'upright': True, 'height': 11.492966154483838, 'width': 28.08632219041142, 'direction': 'ltr'}, {'text': '

In [11]:
pdf_path = r'C:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\Fashionova\B158_91060_20230815_V1916.pdf'

In [12]:
import fitz  # PyMuPDF

HEADER_KEYWORDS = ["description", "qty", "q'ty", "unit", "item", "pegno", "no", "colour", "code", "price"]
FOOTER_KEYWORDS = ["total", "subtotal", "gst", "grand total", "incl", "excl", "amount"]

def print_blocks(title, blocks):
    print(f"\n=== {title.upper()} ===")
    for b in blocks:
        y = b[1]
        content = b[4].strip().replace("\n", " ")
        print(f"Y: {y:.2f} | {content}")

def find_header_footer_indexes(blocks, footer_min_offset=2):
    header_idx = None
    footer_idx = None

    for i, block in enumerate(blocks):
        text = block[4].replace("\n", " ").lower()
        if header_idx is None:
            header_hits = sum(1 for kw in HEADER_KEYWORDS if kw in text)
            if header_hits >= 2:
                header_idx = i
                print(f"✅ HEADER (line items start) detected at Y={block[1]:.2f} | Line: {text}")
        elif i > header_idx + footer_min_offset:
            if any(kw in text for kw in FOOTER_KEYWORDS):
                footer_idx = i
                print(f"✅ FOOTER detected at Y={block[1]:.2f} | Line: {text}")
                break

    return header_idx, footer_idx

# --- Main Logic ---
doc = fitz.open(pdf_path)
page = doc[0]
blocks = page.get_text("blocks")

# Sort by vertical position
sorted_blocks = sorted(blocks, key=lambda b: b[1])

# Find header/footer indexes with a buffer
header_idx, footer_idx = find_header_footer_indexes(sorted_blocks)

if header_idx is None:
    raise ValueError("❌ Header not found — check keywords or invoice layout.")
if footer_idx is None:
    footer_idx = len(sorted_blocks)

# Define areas
top_area = sorted_blocks[:header_idx]
line_items_area = sorted_blocks[header_idx:footer_idx]
bottom_area = sorted_blocks[footer_idx:]

# Print
print_blocks("Top Area", top_area)
print_blocks("Line Items Area", line_items_area)
print_blocks("Bottom Area", bottom_area)

✅ HEADER (line items start) detected at Y=259.72 | Line: no. no. pegno. pegno. type no. type no. size size colour colour description description q'ty q'ty unit unit
✅ FOOTER detected at Y=265.36 | Line: excl.gst

=== TOP AREA ===
Y: 113.34 | Bill  To   :   CW Management Pty Ltd B655 Customer No. : PH1871
Y: 132.42 | Ship  To : Chemist Warehouse Townsville B158 Invoice No. : 91060
Y: 148.74 | Invoice Date : 15.08.23 126-128 Sturt St TOWNSVILLE QLD 4810 AUSTRALIA
Y: 157.39 | Address : Due Date : 30.09.23
Y: 181.26 | Invoice Amount : $ 187.25 AUD
Y: 228.72 | TAX INVOICE TAX INVOICE Page Page 11 of of 11
Y: 252.87 | Unit
Y: 252.87 | Unit
Y: 252.87 | Total
Y: 252.87 | Total
Y: 252.87 | Total
Y: 252.87 | Total

=== LINE ITEMS AREA ===
Y: 259.72 | No. No. PegNo. PegNo. Type No. Type No. Size Size Colour Colour Description Description Q'ty Q'ty Unit Unit
Y: 259.72 | excl.GST GST GST
Y: 265.36 | Price
Y: 265.36 | Price

=== BOTTOM AREA ===
Y: 265.36 | excl.GST
Y: 265.36 | Incl.GST
Y: 265.36 | Incl.GST
Y: 279.88 | 1 D08 D08 TN1-012L-C1 TN1-012L-C1 3-9 3-9 N.PK/OR/YL N.PK/OR/YLLadies' Casual Low cut Ladies' Casual Low cut 1 Dz Dz $42.78 $42.78 $42.78 $42.78 $4.28 $4.28 $47.06 $47.06
Y: 291.28 | 2 D12 D12 TN2-002M-B1 TN2-002M-B1 7-11 7-11 WH WH Men's Casual Anklet Men's Casual Anklet 1 Dz Dz $42.78 $42.78 $42.78 $42.78 $4.28 $4.28 $47.06 $47.06
Y: 302.80 | 3 PD03 PD03 BU4-002K-C2 BU4-002K-C2 11-14 11-14 BK BK Men's Business Diabetic Friendly  Extra Large Men's Business Diabetic Friendly  Extra Large 1 Dz Dz $64.17 $64.17 $64.17 $64.17 $6.42 $6.42 $70.59 $70.59
Y: 314.32 | 4 COU COU COU COU Courier Fee Courier Fee 1 Box Box $20.50 $20.50 $20.50 $20.50 $2.05 $2.05 $22.55 $22.55
Y: 328.72 | Total Q'ty 3 Dz $170.23 $17.02 $187.25 SATCHEL*1
Y: 412.15 | Total (GST Incl.) $187.25 RE-ORDERS & GENERAL ENQUIRIES
Y: 428.18 | - Please fax through Re-Order Form to 02 9748 6211 Due Date 30.09.23 o RE-ORDERS
Y: 444.66 | Last Balance $0.00 for your next order. New Re-Order Forms are supplied with this delivery.
Y: 462.88 | Current Payment $0.00 - Please contact FASHIONOVA at 029748 6222 o ENQUIRIES
Y: 478.94 | Leave your general enquiry on  www.soxnlox.com or e-mail to  info@fashionova.com.au Total Balance $187.25
Y: 510.50 | o All display stands will remain the property of Fashionova Pty Ltd.
Y: 587.11 | How to pay this invoice Fashionova Pty Ltd ABN : 96 125 037 434
Y: 617.13 | Electronic Funds Transfer Cheque in the Mail Credit Card Payment For Visa & Mastercard payments, please complete the following and mail or fax back to 02 9748 6211:
Y: 633.12 | Preferred Method of Payment Please make your cheque payable
Y: 647.73 | to Fashionova Pty Ltd Account ......: Fashionova Pty Ltd Bank ...........: CBA BSB/Acc No : 062 256/1042 5214
Y: 657.00 | Visa ____  Mastercard ____  Expiry:_______/_______
Y: 664.68 | (T/A SOX & LOX)
Y: 680.04 | Name on card: _______________________________
Y: 684.12 | Unit 3 / 10-11 Millennium Court Silverwater NSW 2128
Y: 684.84 | * Please quote  your Customer NO .: Or Invoice NO : for the payment.
Y: 699.36 | PH1871 91060
Y: 702.96 | Card#: ______________________________________
Y: 723.15 | Please note: 1.88% credit card surcharge applies.
Y: 827.49 | Page 1 1 of

In [13]:
import fitz # PyMuPDF

doc = fitz.open(pdf_path)
page = doc.load_page(0) # Load the first page

# Extract text in a structured format (e.g., as a list of blocks)
text_blocks = page.get_text("blocks")

# You would then need to parse these blocks to identify and reconstruct tables

In [15]:
import camelot

tables = camelot.read_pdf(pdf_path, pages="1", flavor="stream")

if tables.n == 0:
    print("No tables found on page 1.")
else:
    print(f"Found {tables.n} tables.")
    print(tables[0].df)

Found 1 tables.
          0       1            2       3                                 4   \
0
1
2     No.No.  PegNo.     Type No.    Size                            Colour
3
4          1  D08D08  TN1-012L-C1  3-93-9  N.PK/OR/YLLadies' Casual Low cut
5          2  D12D12  TN2-002M-B1    7-11                              WHWH
6          3    PD03  BU4-002K-C2   11-14                              BKBK
7          4     COU          COU
8  SATCHEL*1

                                              5         6       7       8   \
0                                    TAX INVOICE
1                                                                     Unit
2                                    Description  Q'tyQ'ty    Unit
3                                                                    Price
4                                                        1    DzDz  $42.78
5                            Men's Casual Anklet         1    DzDz  $42.78
6  Men's Business Diabetic Friendly  Extra Large         1    DzDz  $64.17
7                                    Courier Fee         1  BoxBox  $20.50
8                                     Total Q'ty         3      Dz

                9              10
0             Page     1\nofof\n1
1            Total          Total
2                          GSTGST
3         excl.GST       Incl.GST
4           $42.78  $4.28\n$47.06
5           $42.78  $4.28\n$47.06
6           $64.17  $6.42\n$70.59
7           $20.50  $2.05\n$22.55
8  $170.23\n$17.02        $187.25

In [16]:
import camelot

tables = camelot.read_pdf(pdf_path, pages="1", flavor="stream")
df = tables[0].df

In [17]:
# Drop rows that are all empty or nearly empty
df = df[df.apply(lambda row: row.astype(str).str.strip().str.len().sum() > 5, axis=1)].reset_index(drop=True)
df

,0,1,2,3,4,5,6,7,8,9,10
0,,,,,,TAX INVOICE,,,,Page,1\nofof\n1
1,,,,,,,,,Unit,Total,Total
2,No.No.,PegNo.,Type No.,Size,Colour,Description,Q'tyQ'ty,Unit,,,GSTGST
3,,,,,,,,,Price,excl.GST,Incl.GST
4,1,D08D08,TN1-012L-C1,3-93-9,N.PK/OR/YLLadies' Casual Low cut,,1,DzDz,$42.78,$42.78,$4.28\n$47.06
5,2,D12D12,TN2-002M-B1,7-11,WHWH,Men's Casual Anklet,1,DzDz,$42.78,$42.78,$4.28\n$47.06
6,3,PD03,BU4-002K-C2,11-14,BKBK,Men's Business Diabetic Friendly Extra Large,1,DzDz,$64.17,$64.17,$6.42\n$70.59
7,4,COU,COU,,,Courier Fee,1,BoxBox,$20.50,$20.50,$2.05\n$22.55
8,SATCHEL*1,,,,,Total Q'ty,3,Dz,,$170.23\n$17.02,$187.25

In [18]:
import fitz  # PyMuPDF
import camelot

# Step 1: Extract tables
tables = camelot.read_pdf(pdf_path, pages="1", flavor="stream")

if tables.n == 0:
    print("❌ No tables found.")
    exit()

print(f"✅ Found {tables.n} table(s)")

table = tables[0]
x1, y1, x2, y2 = table._bbox  # Camelot gives (x1, y1, x2, y2) = (left, bottom, right, top)
print(f"📏 Table Bounding Box: L={x1}, B={y1}, R={x2}, T={y2}")

# Step 2: Read blocks from PyMuPDF
doc = fitz.open(pdf_path)
page = doc[0]
blocks = sorted(page.get_text("blocks"), key=lambda b: b[1])  # sort by Y (top)

# Step 3: Classify blocks into regions
top_area = []
line_items_area = []
bottom_area = []

for b in blocks:
    y_top = b[1]
    y_bottom = b[3]
    text = b[4].strip().replace("\n", " ")
    if y_bottom > y2:
        top_area.append((y_top, text))
    elif y_top < y1:
        bottom_area.append((y_top, text))
    else:
        line_items_area.append((y_top, text))

# Step 4: Print each area
def print_blocks(label, area):
    print(f"\n=== {label.upper()} ===")
    for y, text in area:
        print(f"Y: {y:.2f} | {text}")

print_blocks("Top Area", top_area)
print_blocks("Line Items Area", line_items_area)
print_blocks("Bottom Area", bottom_area)

✅ Found 1 table(s)
📏 Table Bounding Box: L=11.118363147372495, B=506.6267957996113, R=579.0975653378011, T=628.2825802854215

=== TOP AREA ===
Y: 617.13 | Electronic Funds Transfer Cheque in the Mail Credit Card Payment For Visa & Mastercard payments, please complete the following and mail or fax back to 02 9748 6211:
Y: 633.12 | Preferred Method of Payment Please make your cheque payable
Y: 647.73 | to Fashionova Pty Ltd Account ......: Fashionova Pty Ltd Bank ...........: CBA BSB/Acc No : 062 256/1042 5214
Y: 657.00 | Visa ____  Mastercard ____  Expiry:_______/_______
Y: 664.68 | (T/A SOX & LOX)
Y: 680.04 | Name on card: _______________________________
Y: 684.12 | Unit 3 / 10-11 Millennium Court Silverwater NSW 2128
Y: 684.84 | * Please quote  your Customer NO .: Or Invoice NO : for the payment.
Y: 699.36 | PH1871 91060
Y: 702.96 | Card#: ______________________________________
Y: 723.15 | Please note: 1.88% credit card surcharge applies.
Y: 827.49 | Page 1 1 of

=== LINE ITEMS AREA ===
Y: 510.50 | o All display stands will remain the property of Fashionova Pty Ltd.
Y: 587.11 | How to pay this invoice Fashionova Pty Ltd ABN : 96 125 037 434

=== BOTTOM AREA ===
Y: 113.34 | Bill  To   :   CW Management Pty Ltd B655 Customer No. : PH1871
Y: 132.42 | Ship  To : Chemist Warehouse Townsville B158 Invoice No. : 91060
Y: 148.74 | Invoice Date : 15.08.23 126-128 Sturt St TOWNSVILLE QLD 4810 AUSTRALIA
Y: 157.39 | Address : Due Date : 30.09.23
Y: 181.26 | Invoice Amount : $ 187.25 AUD
Y: 228.72 | TAX INVOICE TAX INVOICE Page Page 11 of of 11
Y: 252.87 | Unit
Y: 252.87 | Unit
Y: 252.87 | Total
Y: 252.87 | Total
Y: 252.87 | Total
Y: 252.87 | Total
Y: 259.72 | No. No. PegNo. PegNo. Type No. Type No. Size Size Colour Colour Description Description Q'ty Q'ty Unit Unit
Y: 259.72 | excl.GST GST GST
Y: 265.36 | Price
Y: 265.36 | Price
Y: 265.36 | excl.GST
Y: 265.36 | Incl.GST
Y: 265.36 | Incl.GST
Y: 279.88 | 1 D08 D08 TN1-012L-C1 TN1-012L-C1 3-9 3-9 N.PK/OR/YL N.PK/OR/YLLadies' Casual Low cut Ladies' Casual Low cut 1 Dz Dz $42.78 $42.78 $42.78 $42.78 $4.28 $4.28 $47.06 $47.06
Y: 291.28 | 2 D12 D12 TN2-002M-B1 TN2-002M-B1 7-11 7-11 WH WH Men's Casual Anklet Men's Casual Anklet 1 Dz Dz $42.78 $42.78 $42.78 $42.78 $4.28 $4.28 $47.06 $47.06
Y: 302.80 | 3 PD03 PD03 BU4-002K-C2 BU4-002K-C2 11-14 11-14 BK BK Men's Business Diabetic Friendly  Extra Large Men's Business Diabetic Friendly  Extra Large 1 Dz Dz $64.17 $64.17 $64.17 $64.17 $6.42 $6.42 $70.59 $70.59
Y: 314.32 | 4 COU COU COU COU Courier Fee Courier Fee 1 Box Box $20.50 $20.50 $20.50 $20.50 $2.05 $2.05 $22.55 $22.55
Y: 328.72 | Total Q'ty 3 Dz $170.23 $17.02 $187.25 SATCHEL*1
Y: 412.15 | Total (GST Incl.) $187.25 RE-ORDERS & GENERAL ENQUIRIES
Y: 428.18 | - Please fax through Re-Order Form to 02 9748 6211 Due Date 30.09.23 o RE-ORDERS
Y: 444.66 | Last Balance $0.00 for your next order. New Re-Order Forms are supplied with this delivery.
Y: 462.88 | Current Payment $0.00 - Please contact FASHIONOVA at 029748 6222 o ENQUIRIES
Y: 478.94 | Leave your general enquiry on  www.soxnlox.com or e-mail to  info@fashionova.com.au Total Balance $187.25

### Deep OCR

In [8]:
from doctr.io import DocumentFile
from doctr.models import ocr_predictor
from sklearn.cluster import DBSCAN
import numpy as np
import pandas as pd

def load_and_ocr(pdf_path):
    doc = DocumentFile.from_pdf(pdf_path)
    model = ocr_predictor(pretrained=True)
    result = model(doc)
    return result

def get_word_boxes(result):
    words = []
    for page in result.pages:
        for block in page.blocks:
            for line in block.lines:
                for word in line.words:
                    x1, y1 = word.geometry[0]
                    x2, y2 = word.geometry[1]
                    words.append({
                        "text": word.value,
                        "x": (x1 + x2) / 2,
                        "y": (y1 + y2) / 2,
                        "x1": x1,
                        "x2": x2,
                        "y1": y1,
                        "y2": y2,
                    })
    return words

def cluster_by_axis(words, axis='y', eps=0.01, min_samples=1):
    coords = np.array([[w[axis]] for w in words])
    clustering = DBSCAN(eps=eps, min_samples=min_samples).fit(coords)
    for word, label in zip(words, clustering.labels_):
        word[f'{axis}_cluster'] = label
    return words

def build_table(words):
    words = cluster_by_axis(words, 'y', eps=0.01)  # row clustering
    words = cluster_by_axis(words, 'x', eps=0.02)  # column clustering

    rows = {}
    for w in words:
        row_id = w['y_cluster']
        col_id = w['x_cluster']
        if row_id not in rows:
            rows[row_id] = {}
        rows[row_id][col_id] = w['text']

    # Reconstruct grid
    sorted_rows = sorted(rows.items())
    all_cols = sorted({col_id for r in rows.values() for col_id in r})
    table_data = []

    for _, row in sorted_rows:
        line = [row.get(col, "") for col in all_cols]
        table_data.append(line)

    return pd.DataFrame(table_data)

# Run everything
def extract_invoice_table(pdf_path):
    ocr_result = load_and_ocr(pdf_path)
    words = get_word_boxes(ocr_result)
    table_df = build_table(words)
    return table_df

# Example
if __name__ == "__main__":
    path = r"C:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\Invoices\B035_CN-016337_20240906_V1127.pdf"  # Replace with your PDF path
    df = extract_invoice_table(path)
    print(df.to_string(index=False, header=False))

c:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\CompleteWL\lib\site-packages\doctr\models\utils\pytorch.py:59: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(archive_path, map_location="cpu")

       336
      1300
  Integria
       AUS
       844
      copy  HEALTHCARE
 CN-016337
      B655         To:
    Street
      3072
       AUS
SO-0314984
Poari-Down
      Nett    Material
   -105.09   EPTABP150
    -97.61     EPTRN90
   -202.70 Receivable:
       336      Phone:
         %        Fax:
       End      Email:
                Notes:
    133956
     date:
       1/1

In [3]:
path = r"C:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\Fashionova\B158_91060_20230815_V1916.pdf"  # Replace with your PDF path

In [4]:
def build_table(words, min_cols=4, min_tokens=3):
    words = cluster_by_axis(words, 'y', eps=0.01)
    words = cluster_by_axis(words, 'x', eps=0.02)

    rows = {}
    for w in words:
        row_id = w['y_cluster']
        col_id = w['x_cluster']
        if row_id not in rows:
            rows[row_id] = {}
        rows[row_id][col_id] = w['text']

    # Get all unique columns
    all_cols = sorted({col_id for r in rows.values() for col_id in r})
    table_data = []

    for _, row in sorted(rows.items()):
        line = [row.get(col, "") for col in all_cols]
        non_empty = sum(1 for cell in line if cell.strip())
        if non_empty >= min_tokens:
            table_data.append(line)

    return pd.DataFrame(table_data)

def cluster_by_axis(words, axis='y', eps=0.008, min_samples=1):
    coords = np.array([[w[axis]] for w in words])
    clustering = DBSCAN(eps=eps, min_samples=min_samples).fit(coords)
    for word, label in zip(words, clustering.labels_):
        word[f'{axis}_cluster'] = label
    return words

In [5]:
import numpy as np
import pandas as pd
from doctr.io import DocumentFile
from doctr.models import ocr_predictor
from sklearn.cluster import DBSCAN
import re


def is_numeric(val):
    return bool(re.match(r"^-?\d+(\.\d+)?$", val.replace(",", "")))

def cluster_by_axis(words, axis='y', eps=0.01, min_samples=1):
    coords = np.array([[w[axis]] for w in words])
    clustering = DBSCAN(eps=eps, min_samples=min_samples).fit(coords)
    for word, label in zip(words, clustering.labels_):
        word[f'{axis}_cluster'] = label
    return words

def get_word_boxes(result):
    words = []
    for page in result.pages:
        for block in page.blocks:
            for line in block.lines:
                for word in line.words:
                    x1, y1 = word.geometry[0]
                    x2, y2 = word.geometry[1]
                    words.append({
                        "text": word.value,
                        "x": (x1 + x2) / 2,
                        "y": (y1 + y2) / 2,
                        "x1": x1,
                        "x2": x2,
                        "y1": y1,
                        "y2": y2,
                    })
    return words

def build_table(words, min_cols=4, min_tokens=3):
    words = cluster_by_axis(words, 'y', eps=0.008)
    words = cluster_by_axis(words, 'x', eps=0.01)

    rows = {}
    for w in words:
        row_id = w['y_cluster']
        col_id = w['x_cluster']
        if row_id not in rows:
            rows[row_id] = {}
        rows[row_id][col_id] = w['text']

    # Get all unique columns
    all_cols = sorted({col_id for r in rows.values() for col_id in r})
    table_data = []

    for _, row in sorted(rows.items()):
        line = [row.get(col, "") for col in all_cols]
        non_empty = sum(1 for cell in line if cell.strip())
        if non_empty >= min_tokens:
            table_data.append(line)

    df = pd.DataFrame(table_data)

    # Drop very sparse columns
    df = df.loc[:, df.apply(lambda col: col.astype(str).str.strip().astype(bool).sum() > 2)]

    return df.reset_index(drop=True)


def extract_line_items_from_invoice(pdf_path, export_to=None):
    """
    Extracts tabular line items from an invoice using OCR and layout clustering.

    Args:
        pdf_path (str): Path to PDF invoice
        export_to (str): Optional. 'csv' or 'excel' to save the output.

    Returns:
        pd.DataFrame: Extracted line item table
    """
    # Step 1: OCR
    print(f"🔍 Running OCR on: {pdf_path}")
    doc = DocumentFile.from_pdf(pdf_path)
    model = ocr_predictor(pretrained=True)
    result = model(doc)

    # Step 2: Get word layout
    words = get_word_boxes(result)

    if not words:
        print("⚠️ No text found.")
        return pd.DataFrame()

    # Step 3: Build table using layout clustering
    df = build_table(words)

    # Step 4: Save if requested
    if export_to == "csv":
        out_path = pdf_path.replace(".pdf", "_lineitems.csv")
        df.to_csv(out_path, index=False)
        print(f"✅ Saved to: {out_path}")
    elif export_to == "excel":
        out_path = pdf_path.replace(".pdf", "_lineitems.xlsx")
        df.to_excel(out_path, index=False)
        print(f"✅ Saved to: {out_path}")

    return df

if __name__ == "__main__":
    #pdf = "invoice.pdf"
    df = extract_line_items_from_invoice(path, export_to="excel")

    print("\n📦 Final Line Item Table:")
    print(df.to_string(index=False, header=False))

🔍 Running OCR on: C:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\Invoices\B035_CN-016337_20240906_V1127.pdf

c:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\CompleteWL\lib\site-packages\doctr\models\utils\pytorch.py:59: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(archive_path, map_location="cpu")

✅ Saved to: C:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\Invoices\B035_CN-016337_20240906_V1127_lineitems.xlsx

📦 Final Line Item Table:
        PTY LIMITED Customer   1300                 336
70096496212         Customer   1300
       4113            Email      : orders@integria.com  Integria
                                                                  adjustment     note       copy
 Management     Ltd                                       Chemist      Date:          06/09/2024            Ship Elizabeth Street      B035
         44  Street                                           132        No:               55327                 Elizabeth
        VIC    3072                                     MELBOURNE       Ref:                OOD:    x5                 VIC
                                                                         By:              Sheena
        UOM Ordered  Shipped    RRP                List     Brand     Amount Discount       Unit Price  Material                                       Nett
         EA      -2       -2 108.38               65.68     Eagle    (26.27)   20.00%            52.55 EPTABP150           Tresos Activated   PluSe -105.09
         EA      -3       -3  67.11               40.67     Eagle    (24.40)   20.00%            32.54   EPTRN90           Tresos        90 Tablets  -97.61
    032-388   TOTAL                                                                                     Accounts                                to: -202.70 AUD
      55327 Freight                                          1300                                         Phone:       336                             0.00 AUD
                                                             1300                                           Fax:        56
        End                                                                                               Email:                            Payment
 30/11/2024   Final                                                                                                                           date: -222.97 AUD
                GST               %                                  -202.70                                                                         -20.27 AUD

In [6]:
import numpy as np
import pandas as pd
from doctr.io import DocumentFile
from doctr.models import ocr_predictor
from sklearn.cluster import DBSCAN
import re


def is_numeric(val):
    return bool(re.match(r"^-?\d+(\.\d+)?$", val.replace(",", "")))

def cluster_by_axis(words, axis='y', eps=0.01, min_samples=1):
    coords = np.array([[w[axis]] for w in words])
    clustering = DBSCAN(eps=eps, min_samples=min_samples).fit(coords)
    for word, label in zip(words, clustering.labels_):
        word[f'{axis}_cluster'] = label
    return words

def get_word_boxes(result):
    words = []
    for page in result.pages:
        for block in page.blocks:
            for line in block.lines:
                for word in line.words:
                    x1, y1 = word.geometry[0]
                    x2, y2 = word.geometry[1]
                    words.append({
                        "text": word.value,
                        "x": (x1 + x2) / 2,
                        "y": (y1 + y2) / 2,
                        "x1": x1,
                        "x2": x2,
                        "y1": y1,
                        "y2": y2,
                    })
    return words

def build_table(words, min_cols=4, min_tokens=3):
    words = cluster_by_axis(words, 'y', eps=0.008)
    words = cluster_by_axis(words, 'x', eps=0.01)

    rows = {}
    for w in words:
        row_id = w['y_cluster']
        col_id = w['x_cluster']
        if row_id not in rows:
            rows[row_id] = {}
        rows[row_id][col_id] = w['text']

    all_cols = sorted({col_id for r in rows.values() for col_id in r})
    table_data = []
    row_map = []

    for cluster_id, row in sorted(rows.items()):
        line = [row.get(col, "") for col in all_cols]
        non_empty = sum(1 for cell in line if cell.strip())
        if non_empty >= min_tokens:
            table_data.append(line)
            row_map.append(cluster_id)

    df = pd.DataFrame(table_data)
    df = df.loc[:, df.apply(lambda col: col.astype(str).str.strip().astype(bool).sum() > 2)]
    return df.reset_index(drop=True), sorted(row_map)

def extract_header_lineitems_footer(pdf_path):
    print(f"🔍 Running OCR on: {pdf_path}")
    doc = DocumentFile.from_pdf(pdf_path)
    model = ocr_predictor(pretrained=True)
    result = model(doc)

    words = get_word_boxes(result)
    if not words:
        print("⚠️ No text found.")
        return None, None, None

    df, row_ids = build_table(words)

    # Step 1: Identify candidate line item rows (at least 1 number + not sparse)
    numeric_rows = df.apply(lambda row: sum(is_numeric(str(cell)) for cell in row), axis=1)
    valid_rows = numeric_rows >= 1

    # Step 2: Find longest continuous block of valid rows
    max_block = []
    current = []
    for i, is_valid in enumerate(valid_rows):
        if is_valid:
            current.append(i)
        else:
            if len(current) > len(max_block):
                max_block = current
            current = []
    if len(current) > len(max_block):
        max_block = current

    # Step 3: Split
    if not max_block:
        print("⚠️ No line item block detected.")
        return df, None, None

    start, end = max_block[0], max_block[-1] + 1
    header = df.iloc[:start].reset_index(drop=True)
    line_items = df.iloc[start:end].reset_index(drop=True)
    footer = df.iloc[end:].reset_index(drop=True)

    return header, line_items, footer

# Example usage
if __name__ == "__main__":
    pdf_path = "invoice.pdf"
    header, line_items, footer = extract_header_lineitems_footer(path)

    print("\n🧾 Header:")
    print(header.to_string(index=False, header=False))

    print("\n📦 Line Items:")
    print(line_items.to_string(index=False, header=False))

    print("\n📑 Footer:")
    print(footer.to_string(index=False, header=False))

🔍 Running OCR on: C:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\Invoices\B035_CN-016337_20240906_V1127.pdf

c:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\CompleteWL\lib\site-packages\doctr\models\utils\pytorch.py:59: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(archive_path, map_location="cpu")

🧾 Header:
        PTY LIMITED Customer 1300                 336
70096496212         Customer 1300
       4113            Email    : orders@integria.com  Integria
                                                                adjustment     note       copy
 Management     Ltd                                     Chemist      Date:          06/09/2024           Ship Elizabeth Street B035
         44  Street                                         132        No:               55327                Elizabeth
        VIC    3072                                   MELBOURNE       Ref:                OOD:    x5                VIC
                                                                       By:              Sheena
        UOM Ordered  Shipped  RRP                List     Brand     Amount Discount       Unit Price Material                        Nett

📦 Line Items:
     EA      -2 -2 108.38 65.68 Eagle (26.27) 20.00%  52.55 EPTABP150     Tresos Activated   PluSe -105.09
     EA      -3 -3  67.11 40.67 Eagle (24.40) 20.00%  32.54   EPTRN90     Tresos        90 Tablets  -97.61
032-388   TOTAL                                              Accounts                          to: -202.70 AUD
  55327 Freight                  1300                          Phone: 336                             0.00 AUD
                                 1300                            Fax:  56

📑 Footer:
       End                       Email:    Payment
30/11/2024 Final                             date: -222.97 AUD
             GST  %   -202.70                       -20.27 AUD

In [13]:
import numpy as np
import pandas as pd
import pdfplumber
from doctr.io import DocumentFile
from doctr.models import ocr_predictor
from sklearn.cluster import DBSCAN
import re


def is_numeric(val):
    return bool(re.match(r"^-?\d+(\.\d+)?$", val.replace(",", "")))

def cluster_by_axis(words, axis='y', eps=0.01, min_samples=1):
    coords = np.array([[w[axis]] for w in words])
    clustering = DBSCAN(eps=eps, min_samples=min_samples).fit(coords)
    for word, label in zip(words, clustering.labels_):
        word[f'{axis}_cluster'] = label
    return words

def get_word_boxes(result):
    words = []
    for page in result.pages:
        for block in page.blocks:
            for line in block.lines:
                for word in line.words:
                    x1, y1 = word.geometry[0]
                    x2, y2 = word.geometry[1]
                    words.append({
                        "text": word.value,
                        "x": (x1 + x2) / 2,
                        "y": (y1 + y2) / 2,
                        "x1": x1,
                        "x2": x2,
                        "y1": y1,
                        "y2": y2,
                    })
    return words

def clean_ocr_text(text):
    if not isinstance(text, str): return text
    # Remove repeated characters: e.g., UUnniitt → Unit
    text = re.sub(r'(.)\1{1,}', r'\1', text)
    # Fix common OCR misreads like “..” or double quotes
    text = re.sub(r"[“”\"']+", "\"", text)
    return text.strip()

def build_table(words, min_cols=4, min_tokens=3):
    words = cluster_by_axis(words, 'y', eps=0.008)
    words = cluster_by_axis(words, 'x', eps=0.01)

    rows = {}
    for w in words:
        row_id = w['y_cluster']
        col_id = w['x_cluster']
        if row_id not in rows:
            rows[row_id] = {}
        rows[row_id][col_id] = w['text']

    all_cols = sorted({col_id for r in rows.values() for col_id in r})
    table_data = []
    row_map = []

    for cluster_id, row in sorted(rows.items()):
        line = [row.get(col, "") for col in all_cols]
        non_empty = sum(1 for cell in line if cell.strip())
        if non_empty >= min_tokens:
            table_data.append(line)
            row_map.append(cluster_id)

    df = pd.DataFrame(table_data)
    df = df.loc[:, df.apply(lambda col: col.astype(str).str.strip().astype(bool).sum() > 2)]
    return df.reset_index(drop=True), sorted(row_map)

def detect_lineitem_start(df):
    header_keywords = ["Material", "UOM", "Ordered", "Shipped", "RRP", "Unit", "Price", "Discount", "Amount"]
    for i, row in df.iterrows():
        row_text = " ".join(str(cell).lower() for cell in row if isinstance(cell, str))
        if any(keyword.lower() in row_text for keyword in header_keywords):
            return i
    return None

def extract_with_doctr(pdf_path):
    doc = DocumentFile.from_pdf(pdf_path)
    model = ocr_predictor(pretrained=True)
    result = model(doc)
    words = get_word_boxes(result)
    if not words:
        print("⚠️ No text found.")
        return None, None, None

    df, row_ids = build_table(words)
    line_start_idx = detect_lineitem_start(df)
    if line_start_idx is None:
        print("⚠️ Could not detect line item header row.")
        return df, None, None

    line_items = []
    for i in range(line_start_idx + 1, len(df)):
        if df.iloc[i].apply(lambda x: is_numeric(str(x))).sum() >= 1:
            line_items.append(i)
        else:
            break

    start = line_start_idx
    end = line_items[-1] + 1 if line_items else start + 1

    header = df.iloc[:start].reset_index(drop=True)
    line_items_df = df.iloc[start:end].reset_index(drop=True)
    footer = df.iloc[end:].reset_index(drop=True)
    return header, line_items_df, footer

def extract_with_pdfplumber(pdf_path):
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            table = page.extract_table()
            if table:
                df = pd.DataFrame(table[1:], columns=table[0])
                return None, df, None
    return None, None, None

def extract_invoice_items(pdf_path):
    print(f"🔍 Running extraction on: {pdf_path}")
    try:
        _, df, _ = extract_with_pdfplumber(pdf_path)
        if df is not None and len(df.columns) >= 3:
            print("✅ Extracted with pdfplumber.")
            return None, df, None
        else:
            raise ValueError("Fallback to OCR")
    except:
        print("⚠️ Falling back to Doctr OCR.")
        return extract_with_doctr(pdf_path)

# Example usage
if __name__ == "__main__":

    header, line_items, footer = extract_invoice_items(path)
    line_items = line_items.applymap(clean_ocr_text) if line_items is not None else None
    header = header.applymap(clean_ocr_text) if header is not None else None
    footer = footer.applymap(clean_ocr_text) if footer is not None else None


    print("\n🧾 Header:")
    if header is not None:
        print(header.to_string(index=False, header=False))

    print("\n📦 Line Items:")
    if line_items is not None:
        print(line_items.to_string(index=False, header=False))

    print("\n📑 Footer:")
    if footer is not None:
        print(footer.to_string(index=False, header=False))

🔍 Running extraction on: C:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\Fashionova\B158_91060_20230815_V1916.pdf
✅ Extracted with pdfplumber.

🧾 Header:

📦 Line Items:
     None None        None None None None      None None                                        None None Unit   None    None   None   None None    None
     None None        None None None None      None None                                        None None        None    None   None   None None    None
        1  D08 TN1-012L-C1 None  3-9 None N.PK/OR/Y None                      Ladies" Casual Low cut    1   Dz $42.78    None $42.78  $4.28 None  $47.06
        2  D12  TN2-02M-B1 None  7-1 None        WH None                         Men"s Casual Anklet    1   Dz $42.78    None $42.78  $4.28 None  $47.06
        3 PD03  BU4-02K-C2 None 1-14 None        BK None Men"s Busines Diabetic Friendly Extra Large    1   Dz $64.17    None $64.17  $6.42 None  $70.59
        4  COU         COU None      None      None None                                  Courier Fe    1  Box $20.50    None $20.50  $2.05 None    $2.5
SATCHEL*1 None        None None None None      None None                                        None None None        $170.23   None $17.02 None $187.25

📑 Footer:

In [4]:
import numpy as np
import pandas as pd
import pdfplumber
from doctr.io import DocumentFile
from doctr.models import ocr_predictor
from sklearn.cluster import DBSCAN
import re


def is_numeric(val):
    return bool(re.match(r"^-?\d+(\.\d+)?$", val.replace(",", "")))

def clean_ocr_text(text):
    if not isinstance(text, str): return text
    text = re.sub(r'(.)\1{1,}', r'\1', text)  # Remove repeated characters
    text = re.sub(r"[“”\"']+", '"', text)
    return text.strip()

def filter_junk_rows(df):
    if df is None: return None
    df = df.reset_index(drop=True)  # 👈 ensures aligned index
    mask = df.apply(
        lambda row: row.astype(str).str.replace(r'[^a-zA-Z0-9]', '', regex=True).str.len().sum() > 10,
        axis=1
    )
    return df[mask].reset_index(drop=True)

def cluster_by_axis(words, axis='y', eps=0.01, min_samples=1):
    coords = np.array([[w[axis]] for w in words])
    clustering = DBSCAN(eps=eps, min_samples=min_samples).fit(coords)
    for word, label in zip(words, clustering.labels_):
        word[f'{axis}_cluster'] = label
    return words

def get_word_boxes(result):
    words = []
    for page in result.pages:
        for block in page.blocks:
            for line in block.lines:
                for word in line.words:
                    x1, y1 = word.geometry[0]
                    x2, y2 = word.geometry[1]
                    words.append({
                        "text": word.value,
                        "x": (x1 + x2) / 2,
                        "y": (y1 + y2) / 2,
                        "x1": x1,
                        "x2": x2,
                        "y1": y1,
                        "y2": y2,
                    })
    return words

def build_table(words, min_cols=4, min_tokens=3):
    words = cluster_by_axis(words, 'y', eps=0.008)
    words = cluster_by_axis(words, 'x', eps=0.01)

    rows = {}
    for w in words:
        row_id = w['y_cluster']
        col_id = w['x_cluster']
        if row_id not in rows:
            rows[row_id] = {}
        rows[row_id][col_id] = w['text']

    all_cols = sorted({col_id for r in rows.values() for col_id in r})
    table_data = []
    row_map = []

    for cluster_id, row in sorted(rows.items()):
        line = [row.get(col, "") for col in all_cols]
        non_empty = sum(1 for cell in line if cell.strip())
        if non_empty >= min_tokens:
            table_data.append(line)
            row_map.append(cluster_id)

    df = pd.DataFrame(table_data)
    df = df.loc[:, df.apply(lambda col: col.astype(str).str.strip().astype(bool).sum() > 2)]
    return df.reset_index(drop=True), sorted(row_map)

def detect_lineitem_start(df):
    header_keywords = ["Material", "UOM", "Description", "Ordered", "Shipped", "RRP", "Unit", "Price", "Discount", "Amount"]
    for i, row in df.iterrows():
        row_text = " ".join(str(cell).lower() for cell in row if isinstance(cell, str))
        if any(keyword.lower() in row_text for keyword in header_keywords):
            return i
    return None

def extract_with_doctr(pdf_path):
    doc = DocumentFile.from_pdf(pdf_path)
    model = ocr_predictor(pretrained=True)
    result = model(doc)
    words = get_word_boxes(result)
    if not words:
        print("⚠️ No text found.")
        return None, None, None

    df, row_ids = build_table(words)
    line_start_idx = detect_lineitem_start(df)
    if line_start_idx is None:
        print("⚠️ Could not detect line item header row.")
        return df, None, None

    line_items = []
    for i in range(line_start_idx + 1, len(df)):
        if df.iloc[i].apply(lambda x: is_numeric(str(x))).sum() >= 1:
            line_items.append(i)
        else:
            break

    start = line_start_idx
    end = line_items[-1] + 1 if line_items else start + 1

    header = df.iloc[:start].reset_index(drop=True)
    line_items_df = df.iloc[start:end].reset_index(drop=True)
    footer = df.iloc[end:].reset_index(drop=True)
    return header, line_items_df, footer

def extract_with_pdfplumber(pdf_path):
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            table = page.extract_table()
            if table:
                df = pd.DataFrame(table[1:], columns=table[0])
                return None, df, None
    return None, None, None

def extract_invoice_items(pdf_path):
    print(f"🔍 Running extraction on: {pdf_path}")
    try:
        _, df, _ = extract_with_pdfplumber(pdf_path)
        if df is not None and len(df.columns) >= 3:
            print("✅ Extracted with pdfplumber.")
            header = footer = None
            line_items = df.reset_index(drop=True)
        else:
            raise ValueError("Fallback to OCR")
    except:
        print("⚠️ Falling back to Doctr OCR.")
        header, line_items, footer = extract_with_doctr(pdf_path)

    # Clean and filter all parts
    for part in ['header', 'line_items', 'footer']:
        obj = locals().get(part)
        if obj is not None:
            obj = obj.applymap(clean_ocr_text)
            obj = filter_junk_rows(obj)
            if part == 'header': header = obj
            elif part == 'line_items': line_items = obj
            elif part == 'footer': footer = obj

    return header, line_items, footer

# Example usage
if __name__ == "__main__":
    # pdf_path = "invoice.pdf"
    header, line_items, footer = extract_invoice_items(path)

    print("\n🧾 Header:")
    if header is not None:
        print(header.to_string(index=False, header=False))

    print("\n📦 Line Items:")
    if line_items is not None:
        print(line_items.to_string(index=False, header=False))

    print("\n📑 Footer:")
    if footer is not None:
        print(footer.to_string(index=False, header=False))

🔍 Running extraction on: C:\Users\Govind\Downloads\Work_And\Self_Learning\Invoice_Extraction_demo\Fashionova\B158_91060_20230815_V1916.pdf
✅ Extracted with pdfplumber.

🧾 Header:

📦 Line Items:
     None None        None None None None      None None                                        None None Unit   None    None   None   None None    None
     None None        None None None None      None None                                        None None        None    None   None   None None    None
        1  D08 TN1-012L-C1 None  3-9 None N.PK/OR/Y None                      Ladies" Casual Low cut    1   Dz $42.78    None $42.78  $4.28 None  $47.06
        2  D12  TN2-02M-B1 None  7-1 None        WH None                         Men"s Casual Anklet    1   Dz $42.78    None $42.78  $4.28 None  $47.06
        3 PD03  BU4-02K-C2 None 1-14 None        BK None Men"s Busines Diabetic Friendly Extra Large    1   Dz $64.17    None $64.17  $6.42 None  $70.59
        4  COU         COU None      None      None None                                  Courier Fe    1  Box $20.50    None $20.50  $2.05 None    $2.5
SATCHEL*1 None        None None None None      None None                                        None None None        $170.23   None $17.02 None $187.25

📑 Footer:

In [5]:
line_items

,NNoo..,PPeeggNNoo..,TTyyppee NNoo..,SSiizzee,None,CCoolloouurr,None,DDeessccrriippttiioonn,None,QQ''ttyy,,UUnniitt\nPPrriiccee,None,TToottaall\neexxccll..GGSSTT,,GGSSTT,TToottaall\nIInnccll..GGSSTT
0,None,None,None,None,None,None,None,None,None,None,Unit,None,None,None,None,None,None
1,None,None,None,None,None,None,None,None,None,None,,None,None,None,None,None,None
2,1,D08,TN1-012L-C1,None,3-9,None,N.PK/OR/Y,None,"Ladies"" Casual Low cut",1,Dz,$42.78,None,$42.78,$4.28,None,$47.06
3,2,D12,TN2-02M-B1,None,7-1,None,WH,None,"Men""s Casual Anklet",1,Dz,$42.78,None,$42.78,$4.28,None,$47.06
4,3,PD03,BU4-02K-C2,None,1-14,None,BK,None,"Men""s Busines Diabetic Friendly Extra Large",1,Dz,$64.17,None,$64.17,$6.42,None,$70.59
5,4,COU,COU,None,,None,None,None,Courier Fe,1,Box,$20.50,None,$20.50,$2.05,None,$2.5
6,SATCHEL*1,None,None,None,None,None,None,None,None,None,None,,$170.23,None,$17.02,None,$187.25

In [6]:
# if line_items is not None and not line_items.empty:
#     line_items.columns = [clean_ocr_text(col) if col is not None else "" for col in line_items.columns]
def fix_column_alignment_and_merge(df):
    import numpy as np

    # Step 1: Clean column names
    df.columns = [clean_ocr_text(str(col)) if col else None for col in df.columns]

    # Step 2: For None-named columns, try to merge values into adjacent valid columns
    cols = df.columns.tolist()
    new_df = df.copy()

    for idx, col in enumerate(cols):
        if col is None or col.strip() == "":
            col_data = new_df.iloc[:, idx]
            if col_data.dropna().astype(str).str.strip().any():
                # Prefer to merge to the column on the left if it's named
                if idx > 0 and cols[idx - 1] is not None:
                    left_col = cols[idx - 1]
                    new_df[left_col] = new_df[left_col].combine_first(col_data)
                # Otherwise, try the right
                elif idx < len(cols) - 1 and cols[idx + 1] is not None:
                    right_col = cols[idx + 1]
                    new_df[right_col] = new_df[right_col].combine_first(col_data)
    
    # Step 3: Drop all columns where:
    # - column name is None or empty string AND
    # - all values are None or empty
    clean_cols = []
    for idx, col in enumerate(cols):
        col_data = new_df.iloc[:, idx]
        if col is not None and col.strip() != "":
            clean_cols.append(col)
        elif col_data.dropna().astype(str).str.strip().any():
            clean_cols.append(None)  # Keep it with a default name if it has data

    return new_df.loc[:, clean_cols].reset_index(drop=True)


line_items = fix_column_alignment_and_merge(line_items)

In [ ]:
line_items

,No.,PegNo.,Type No.,Size,Colour,Description,"Q""ty",Unit\nPrice,Total\nexcl.GST,GST,Total\nIncl.GST
0,None,None,None,None,None,None,Unit,None,None,None,None
1,None,None,None,None,None,None,,None,None,None,None
2,1,D08,TN1-012L-C1,3-9,N.PK/OR/Y,"Ladies"" Casual Low cut",1,$42.78,$42.78,None,$47.06
3,2,D12,TN2-02M-B1,7-1,WH,"Men""s Casual Anklet",1,$42.78,$42.78,None,$47.06
4,3,PD03,BU4-02K-C2,1-14,BK,"Men""s Busines Diabetic Friendly Extra Large",1,$64.17,$64.17,None,$70.59
5,4,COU,COU,,None,Courier Fe,1,$20.50,$20.50,None,$2.5
6,SATCHEL*1,None,None,None,None,None,None,,$17.02,None,$187.25

In [ ]:
line_items.drop(line_items[None], axis= 1)

,No.,PegNo.,Type No.,Size,None,None,None,None,None,None,...,None,Total\nexcl.GST,None,None,None,None,None,None,GST,Total\nIncl.GST
0,None,None,None,None,None,None,None,Unit,None,None,...,None,None,None,None,None,Unit,None,None,None,None
1,None,None,None,None,None,None,None,,None,None,...,None,None,None,None,None,,None,None,None,None
2,1,D08,TN1-012L-C1,3-9,3-9,N.PK/OR/Y,"Ladies"" Casual Low cut",Dz,None,$4.28,...,$4.28,$42.78,3-9,N.PK/OR/Y,"Ladies"" Casual Low cut",Dz,None,$4.28,None,$47.06
3,2,D12,TN2-02M-B1,7-1,7-1,WH,"Men""s Casual Anklet",Dz,None,$4.28,...,$4.28,$42.78,7-1,WH,"Men""s Casual Anklet",Dz,None,$4.28,None,$47.06
4,3,PD03,BU4-02K-C2,1-14,1-14,BK,"Men""s Busines Diabetic Friendly Extra Large",Dz,None,$6.42,...,$6.42,$64.17,1-14,BK,"Men""s Busines Diabetic Friendly Extra Large",Dz,None,$6.42,None,$70.59
5,4,COU,COU,,,None,Courier Fe,Box,None,$2.05,...,$2.05,$20.50,,None,Courier Fe,Box,None,$2.05,None,$2.5
6,SATCHEL*1,None,None,None,None,None,None,None,$170.23,$17.02,...,$17.02,$17.02,None,None,None,None,$170.23,$17.02,None,$187.25